#ifndef __OSS_1_0_SH_MASK_H__
#define __OSS_1_0_SH_MASK_H__

#define SRBM_STATUS__MCC_BUSY_MASK                                            0x00000800
#define SRBM_STATUS__MCC_BUSY__SHIFT                                          11
#define SRBM_STATUS__IH_BUSY_MASK                                             0x00020000
#define SRBM_STATUS__IH_BUSY__SHIFT                                           17
#define SRBM_STATUS__SEM_BUSY_MASK                                            0x00004000
#define SRBM_STATUS__SEM_BUSY__SHIFT                                          14
#define SRBM_STATUS__MCB_BUSY_MASK                                            0x00000200
#define SRBM_STATUS__MCB_BUSY__SHIFT                                          9
#define SRBM_STATUS__GRBM_RQ_PENDING_MASK                                     0x00000020
#define SRBM_STATUS__GRBM_RQ_PENDING__SHIFT                                   5
#define SRBM_STATUS__VMC_BUSY_MASK                                            0x00000100
#define SRBM_STATUS__VMC_BUSY__SHIFT                                          8
#define SRBM_STATUS__MCD_BUSY_MASK                                            0x00001000
#define SRBM_STATUS__MCD_BUSY__SHIFT                                          12
#define SRBM_STATUS__MCB_NON_DISPLAY_BUSY_MASK                                0x00000400
#define SRBM_STATUS__MCB_NON_DISPLAY_BUSY__SHIFT                              10
#define SRBM_SOFT_RESET__SOFT_RESET_GRBM_MASK                                 0x00000100
#define SRBM_SOFT_RESET__SOFT_RESET_GRBM__SHIFT                               8
#define SRBM_SOFT_RESET__SOFT_RESET_ORB_MASK                                  0x00800000
#define SRBM_SOFT_RESET__SOFT_RESET_ORB__SHIFT                                23
#define SRBM_SOFT_RESET__SOFT_RESET_TST_MASK                                  0x00200000
#define SRBM_SOFT_RESET__SOFT_RESET_TST__SHIFT                                21
#define SRBM_SOFT_RESET__SOFT_RESET_DC_MASK                                   0x00000020
#define SRBM_SOFT_RESET__SOFT_RESET_DC__SHIFT                                 5
#define SRBM_SOFT_RESET__SOFT_RESET_DMA1_MASK                                 0x00000040
#define SRBM_SOFT_RESET__SOFT_RESET_DMA1__SHIFT                               6
#define SRBM_SOFT_RESET__SOFT_RESET_VMC_MASK                                  0x00020000
#define SRBM_SOFT_RESET__SOFT_RESET_VMC__SHIFT                                17
#define SRBM_SOFT_RESET__SOFT_RESET_SEM_MASK                                  0x00008000
#define SRBM_SOFT_RESET__SOFT_RESET_SEM__SHIFT                                15
#define SRBM_SOFT_RESET__SOFT_RESET_HDP_MASK                                  0x00000200
#define SRBM_SOFT_RESET__SOFT_RESET_HDP__SHIFT                                9
#define SRBM_SOFT_RESET__SOFT_RESET_BIF_MASK                                  0x00000002
#define SRBM_SOFT_RESET__SOFT_RESET_BIF__SHIFT                                1
#define SRBM_SOFT_RESET__SOFT_RESET_IH_MASK                                   0x00000400
#define SRBM_SOFT_RESET__SOFT_RESET_IH__SHIFT                                 10
#define SRBM_SOFT_RESET__SOFT_RESET_REGBB_MASK                                0x00400000
#define SRBM_SOFT_RESET__SOFT_RESET_REGBB__SHIFT                              22
#define SRBM_SOFT_RESET__SOFT_RESET_DMA_MASK                                  0x00100000
#define SRBM_SOFT_RESET__SOFT_RESET_DMA__SHIFT                                20
#define SRBM_SOFT_RESET__SOFT_RESET_MC_MASK                                   0x00000800
#define SRBM_SOFT_RESET__SOFT_RESET_MC__SHIFT                                 11
#define SRBM_SOFT_RESET__SOFT_RESET_ROM_MASK                                  0x00004000
#define SRBM_SOFT_RESET__SOFT_RESET_ROM__SHIFT                                14
#define SRBM_STATUS2__DMA1_BUSY_MASK                                          0x00000040
#define SRBM_STATUS2__DMA1_BUSY__SHIFT                                        6
#define SRBM_STATUS2__DMA_BUSY_MASK                                           0x00000020
#define SRBM_STATUS2__DMA_BUSY__SHIFT                                         5
#define HDP_HOST_PATH_CNTL__CLOCK_GATING_DIS_MASK                             0x00800000
#define HDP_HOST_PATH_CNTL__CLOCK_GATING_DIS__SHIFT                           23
#define HDP_MISC_CNTL__HDP_FLUSH_INVALIDATE_CACHE_MASK                        0x00000001
#define HDP_MISC_CNTL__HDP_FLUSH_INVALIDATE_CACHE__SHIFT                      0
#define HDP_MEM_POWER_LS__HDP_LS_ENABLE_MASK                                  0x00000001
#define HDP_MEM_POWER_LS__HDP_LS_ENABLE__SHIFT                                0
#define IH_RB_CNTL__IH_RB_ENABLE_MASK                                         0x00000001
#define IH_RB_CNTL__IH_RB_ENABLE__SHIFT                                       0
#define IH_RB_CNTL__IH_WPTR_OVERFLOW_CLEAR_MASK                               0x80000000
#define IH_RB_CNTL__IH_WPTR_OVERFLOW_CLEAR__SHIFT                             31
#define IH_RB_CNTL__IH_WPTR_WRITEBACK_ENABLE_MASK                             0x00000100
#define IH_RB_CNTL__IH_WPTR_WRITEBACK_ENABLE__SHIFT                           8
#define IH_RB_CNTL__IH_RB_FULL_DRAIN_ENABLE_MASK                              0x00000040
#define IH_RB_CNTL__IH_RB_FULL_DRAIN_ENABLE__SHIFT                            6
#define IH_RB_CNTL__IH_WPTR_OVERFLOW_ENABLE_MASK                              0x00010000
#define IH_RB_CNTL__IH_WPTR_OVERFLOW_ENABLE__SHIFT                            16
#define IH_RB_WPTR__WPTR_OFFSET_MASK                                          0x3fffc
#define IH_RB_WPTR__WPTR_OFFSET__SHIFT                                        2
#define IH_RB_WPTR__RB_OVERFLOW_MASK                                          0x00000001
#define IH_RB_WPTR__RB_OVERFLOW__SHIFT                                        0
#define IH_CNTL__ENABLE_INTR_MASK                                             0x00000001
#define IH_CNTL__ENABLE_INTR__SHIFT                                           0
#define IH_CNTL__RPTR_REARM_MASK                                              0x00000010
#define IH_CNTL__RPTR_REARM__SHIFT                                            4
#define DMA_RB_CNTL__DMA_RPTR_WRITEBACK_SWAP_ENABLE_MASK                      0x00002000
#define DMA_RB_CNTL__DMA_RPTR_WRITEBACK_SWAP_ENABLE__SHIFT                    13
#define DMA_RB_CNTL__DMA_RPTR_WRITEBACK_ENABLE_MASK                           0x00001000
#define DMA_RB_CNTL__DMA_RPTR_WRITEBACK_ENABLE__SHIFT                         12
#define DMA_RB_CNTL__DMA_RB_ENABLE_MASK                                       0x00000001
#define DMA_RB_CNTL__DMA_RB_ENABLE__SHIFT                                     0
#define DMA_RB_CNTL__DMA_RB_SWAP_ENABLE_MASK                                  0x00000200
#define DMA_RB_CNTL__DMA_RB_SWAP_ENABLE__SHIFT                                9
#define DMA_IB_CNTL__DMA_IB_SWAP_ENABLE_MASK                                  0x00000010
#define DMA_IB_CNTL__DMA_IB_SWAP_ENABLE__SHIFT                                4
#define DMA_IB_CNTL__DMA_IB_ENABLE_MASK                                       0x00000001
#define DMA_IB_CNTL__DMA_IB_ENABLE__SHIFT                                     0
#define DMA_CNTL__DATA_SWAP_ENABLE_MASK                                       0x00000008
#define DMA_CNTL__DATA_SWAP_ENABLE__SHIFT                                     3
#define DMA_CNTL__SEM_WAIT_INT_ENABLE_MASK                                    0x00000004
#define DMA_CNTL__SEM_WAIT_INT_ENABLE__SHIFT                                  2
#define DMA_CNTL__FENCE_SWAP_ENABLE_MASK                                      0x00000010
#define DMA_CNTL__FENCE_SWAP_ENABLE__SHIFT                                    4
#define DMA_CNTL__CTXEMPTY_INT_ENABLE_MASK                                    0x10000000
#define DMA_CNTL__CTXEMPTY_INT_ENABLE__SHIFT                                  28
#define DMA_CNTL__SEM_INCOMPLETE_INT_ENABLE_MASK                              0x00000002
#define DMA_CNTL__SEM_INCOMPLETE_INT_ENABLE__SHIFT                            1
#define DMA_CNTL__TRAP_ENABLE_MASK                                            0x00000001
#define DMA_CNTL__TRAP_ENABLE__SHIFT                                          0
#define DMA_STATUS_REG__DMA_IDLE_MASK                                         0x00000001
#define DMA_STATUS_REG__DMA_IDLE__SHIFT                                       0
#define DMA_POWER_CNTL__MEM_POWER_OVERRIDE_MASK                               0x00000100
#define DMA_POWER_CNTL__MEM_POWER_OVERRIDE__SHIFT                             8
#define DMA_PG__PG_CNTL_ENABLE_MASK                                           0x00000001
#define DMA_PG__PG_CNTL_ENABLE__SHIFT                                         0

#endif /*__OSS_1_0_SH_MASK_H__*/
