#ifndef __OTHER_SI_SH_MASK_H__
#define __OTHER_SI_SH_MASK_H__

#define PIPE0_DMIF_BUFFER_CONTROL__DMIF_BUFFERS_ALLOCATED_COMPLETED_MASK      0x00000010
#define PIPE0_DMIF_BUFFER_CONTROL__DMIF_BUFFERS_ALLOCATED_COMPLETED__SHIFT    4
#define MCLK_PWRMGT_CNTL__MRDCK0_PDNB_MASK                                    0x00000100
#define MCLK_PWRMGT_CNTL__MRDCK0_PDNB__SHIFT                                  8
#define MCLK_PWRMGT_CNTL__MRDCK0_RESET_MASK                                   0x00010000
#define MCLK_PWRMGT_CNTL__MRDCK0_RESET__SHIFT                                 16
#define MCLK_PWRMGT_CNTL__MC_INT_CNTL_MASK                                    0x00000080
#define MCLK_PWRMGT_CNTL__MC_INT_CNTL__SHIFT                                  7
#define MCLK_PWRMGT_CNTL__MRDCK1_PDNB_MASK                                    0x00000200
#define MCLK_PWRMGT_CNTL__MRDCK1_PDNB__SHIFT                                  9
#define MCLK_PWRMGT_CNTL__DLL_READY_MASK                                      0x00000040
#define MCLK_PWRMGT_CNTL__DLL_READY__SHIFT                                    6
#define MCLK_PWRMGT_CNTL__MRDCK1_RESET_MASK                                   0x00020000
#define MCLK_PWRMGT_CNTL__MRDCK1_RESET__SHIFT                                 17
#define MCLK_PWRMGT_CNTL__DLL_READY_READ_MASK                                 0x01000000
#define MCLK_PWRMGT_CNTL__DLL_READY_READ__SHIFT                               24
#define DLL_CNTL__MRDCK0_BYPASS_MASK                                          0x01000000
#define DLL_CNTL__MRDCK0_BYPASS__SHIFT                                        24
#define DLL_CNTL__MRDCK1_BYPASS_MASK                                          0x02000000
#define DLL_CNTL__MRDCK1_BYPASS__SHIFT                                        25
#define PRIORITY_A_CNT__PRIORITY_OFF_MASK                                     0x00010000
#define PRIORITY_A_CNT__PRIORITY_OFF__SHIFT                                   16
#define PRIORITY_A_CNT__PRIORITY_MARK_MASK                                    0x7fff
#define PRIORITY_A_CNT__PRIORITY_MARK__SHIFT                                  0
#define PRIORITY_A_CNT__PRIORITY_ALWAYS_ON_MASK                               0x00100000
#define PRIORITY_A_CNT__PRIORITY_ALWAYS_ON__SHIFT                             20
#define SPI_CONFIG_CNTL_1__INTERP_ONE_PRIM_PER_ROW_MASK                       0x00000010
#define SPI_CONFIG_CNTL_1__INTERP_ONE_PRIM_PER_ROW__SHIFT                     4
#define CGTS_USER_TCC_DISABLE__TCC_DISABLE_MASK                               0xFFFF0000
#define CGTS_USER_TCC_DISABLE__TCC_DISABLE__SHIFT                             16
#define CGTS_SM_CTRL_REG__OVERRIDE_MASK                                       0x00200000
#define CGTS_SM_CTRL_REG__OVERRIDE__SHIFT                                     21
#define CGTS_SM_CTRL_REG__LS_OVERRIDE_MASK                                    0x00400000
#define CGTS_SM_CTRL_REG__LS_OVERRIDE__SHIFT                                  22
#define PACKET3_STRMOUT_BUFFER_UPDATE__WR_CONFIRM_MASK                        0x00100000
#define PACKET3_STRMOUT_BUFFER_UPDATE__WR_CONFIRM__SHIFT                      20
#define PACKET3_STRMOUT_BUFFER_UPDATE__WR_ONE_ADDR_MASK                       0x00010000
#define PACKET3_STRMOUT_BUFFER_UPDATE__WR_ONE_ADDR__SHIFT                     16
#define PACKET3_COPY_DATA__PACKET3_CB2_DEST_BASE_ENA_MASK                     0x00000100
#define PACKET3_COPY_DATA__PACKET3_CB2_DEST_BASE_ENA__SHIFT                   8
#define PACKET3_COPY_DATA__PACKET3_SH_ICACHE_ACTION_ENA_MASK                  0x20000000
#define PACKET3_COPY_DATA__PACKET3_SH_ICACHE_ACTION_ENA__SHIFT                29
#define PACKET3_COPY_DATA__PACKET3_CB5_DEST_BASE_ENA_MASK                     0x00000800
#define PACKET3_COPY_DATA__PACKET3_CB5_DEST_BASE_ENA__SHIFT                   11
#define PACKET3_COPY_DATA__PACKET3_SH_KCACHE_ACTION_ENA_MASK                  0x08000000
#define PACKET3_COPY_DATA__PACKET3_SH_KCACHE_ACTION_ENA__SHIFT                27
#define PACKET3_COPY_DATA__PACKET3_DB_ACTION_ENA_MASK                         0x04000000
#define PACKET3_COPY_DATA__PACKET3_DB_ACTION_ENA__SHIFT                       26
#define PACKET3_COPY_DATA__PACKET3_TCL1_ACTION_ENA_MASK                       0x00400000
#define PACKET3_COPY_DATA__PACKET3_TCL1_ACTION_ENA__SHIFT                     22
#define PACKET3_COPY_DATA__PACKET3_DEST_BASE_0_ENA_MASK                       0x00000001
#define PACKET3_COPY_DATA__PACKET3_DEST_BASE_0_ENA__SHIFT                     0
#define PACKET3_COPY_DATA__PACKET3_CB4_DEST_BASE_ENA_MASK                     0x00000400
#define PACKET3_COPY_DATA__PACKET3_CB4_DEST_BASE_ENA__SHIFT                   10
#define PACKET3_COPY_DATA__PACKET3_DB_DEST_BASE_ENA_MASK                      0x00004000
#define PACKET3_COPY_DATA__PACKET3_DB_DEST_BASE_ENA__SHIFT                    14
#define PACKET3_COPY_DATA__PACKET3_CB0_DEST_BASE_ENA_MASK                     0x00000040
#define PACKET3_COPY_DATA__PACKET3_CB0_DEST_BASE_ENA__SHIFT                   6
#define PACKET3_COPY_DATA__PACKET3_CP_DMA_CMD_SAS_MASK                        0x04000000
#define PACKET3_COPY_DATA__PACKET3_CP_DMA_CMD_SAS__SHIFT                      26
#define PACKET3_COPY_DATA__PACKET3_CB1_DEST_BASE_ENA_MASK                     0x00000080
#define PACKET3_COPY_DATA__PACKET3_CB1_DEST_BASE_ENA__SHIFT                   7
#define PACKET3_COPY_DATA__PACKET3_CB6_DEST_BASE_ENA_MASK                     0x00001000
#define PACKET3_COPY_DATA__PACKET3_CB6_DEST_BASE_ENA__SHIFT                   12
#define PACKET3_COPY_DATA__PACKET3_CP_DMA_CP_SYNC_MASK                        0x80000000
#define PACKET3_COPY_DATA__PACKET3_CP_DMA_CP_SYNC__SHIFT                      31
#define PACKET3_COPY_DATA__PACKET3_CP_DMA_DIS_WC_MASK                         0x00200000
#define PACKET3_COPY_DATA__PACKET3_CP_DMA_DIS_WC__SHIFT                       21
#define PACKET3_COPY_DATA__PACKET3_CP_DMA_CMD_DAS_MASK                        0x08000000
#define PACKET3_COPY_DATA__PACKET3_CP_DMA_CMD_DAS__SHIFT                      27
#define PACKET3_COPY_DATA__PACKET3_DEST_BASE_1_ENA_MASK                       0x00000002
#define PACKET3_COPY_DATA__PACKET3_DEST_BASE_1_ENA__SHIFT                     1
#define PACKET3_COPY_DATA__PACKET3_DEST_BASE_2_ENA_MASK                       0x00080000
#define PACKET3_COPY_DATA__PACKET3_DEST_BASE_2_ENA__SHIFT                     19
#define PACKET3_COPY_DATA__PACKET3_CB_ACTION_ENA_MASK                         0x02000000
#define PACKET3_COPY_DATA__PACKET3_CB_ACTION_ENA__SHIFT                       25
#define PACKET3_COPY_DATA__PACKET3_TC_ACTION_ENA_MASK                         0x00800000
#define PACKET3_COPY_DATA__PACKET3_TC_ACTION_ENA__SHIFT                       23
#define PACKET3_COPY_DATA__PACKET3_DEST_BASE_3_ENA_MASK                       0x00200000
#define PACKET3_COPY_DATA__PACKET3_DEST_BASE_3_ENA__SHIFT                     21
#define PACKET3_COPY_DATA__PACKET3_CB3_DEST_BASE_ENA_MASK                     0x00000200
#define PACKET3_COPY_DATA__PACKET3_CB3_DEST_BASE_ENA__SHIFT                   9
#define PACKET3_COPY_DATA__PACKET3_CP_DMA_CMD_SAIC_MASK                       0x10000000
#define PACKET3_COPY_DATA__PACKET3_CP_DMA_CMD_SAIC__SHIFT                     28
#define PACKET3_COPY_DATA__PACKET3_CP_DMA_CMD_RAW_WAIT_MASK                   0x40000000
#define PACKET3_COPY_DATA__PACKET3_CP_DMA_CMD_RAW_WAIT__SHIFT                 30
#define PACKET3_COPY_DATA__PACKET3_CP_DMA_CMD_DAIC_MASK                       0x20000000
#define PACKET3_COPY_DATA__PACKET3_CP_DMA_CMD_DAIC__SHIFT                     29
#define PACKET3_COPY_DATA__PACKET3_CB7_DEST_BASE_ENA_MASK                     0x00002000
#define PACKET3_COPY_DATA__PACKET3_CB7_DEST_BASE_ENA__SHIFT                   13
#define PACKET3_ME_INITIALIZE__INV_L2_MASK                                    0x00100000
#define PACKET3_ME_INITIALIZE__INV_L2__SHIFT                                  20
#define PACKET3_EVENT_WRITE_EOS__PACKET3_PREAMBLE_END_CLEAR_STATE_MASK        0x30000000
#define PACKET3_EVENT_WRITE_EOS__PACKET3_PREAMBLE_END_CLEAR_STATE__SHIFT      28
#define PACKET3_EVENT_WRITE_EOS__PACKET3_PREAMBLE_BEGIN_CLEAR_STATE_MASK      0x20000000
#define PACKET3_EVENT_WRITE_EOS__PACKET3_PREAMBLE_BEGIN_CLEAR_STATE__SHIFT    28

#endif /*__OTHER_SI_SH_MASK_H__*/
