#ifndef __OTHER_SI_D_H__
#define __OTHER_SI_D_H__

#define mmMCLK_PWRMGT_CNTL                                                      0xae8
#define mmDLL_CNTL                                                              0xae9
#define mmSCRATCH_REG0                                                          0x2140
#define mmSCRATCH_REG1                                                          0x2141
#define mmSCRATCH_REG2                                                          0x2142
#define mmSCRATCH_REG3                                                          0x2143
#define mmSCRATCH_REG4                                                          0x2144
#define mmSCRATCH_REG5                                                          0x2145
#define mmSCRATCH_REG6                                                          0x2146
#define mmSCRATCH_REG7                                                          0x2147
#define mmSCRATCH_UMSK                                                          0x2150
#define mmSCRATCH_ADDR                                                          0x2151
#define mmVGT_VTX_VECT_EJECT_REG                                                0x222c
#define mmVGT_CACHE_INVALIDATION                                                0x2231
#define mmVGT_ESGS_RING_SIZE                                                    0x2232
#define mmVGT_GSVS_RING_SIZE                                                    0x2233
#define mmVGT_GS_VERTEX_REUSE                                                   0x2235
#define mmVGT_PRIMITIVE_TYPE                                                    0x2256
#define mmVGT_INDEX_TYPE                                                        0x2257
#define mmVGT_NUM_INDICES                                                       0x225c
#define mmVGT_NUM_INSTANCES                                                     0x225d
#define mmVGT_TF_RING_SIZE                                                      0x2262
#define mmVGT_HS_OFFCHIP_PARAM                                                  0x226c
#define mmVGT_TF_MEMORY_BASE                                                    0x226e
#define mmSQ_CONFIG                                                             0x2300
#define mmSQC_CACHES                                                            0x2302
#define mmSX_DEBUG_1                                                            0x2418
#define mmSPI_STATIC_THREAD_MGMT_1                                              0x2438
#define mmSPI_STATIC_THREAD_MGMT_2                                              0x2439
#define mmSPI_STATIC_THREAD_MGMT_3                                              0x243a
#define mmSPI_PS_MAX_WAVE_ID                                                    0x243b
#define mmSPI_CONFIG_CNTL                                                       0x2440
#define mmSPI_CONFIG_CNTL_1                                                     0x244f
#define mmCGTS_TCC_DISABLE                                                      0x2452
#define mmCGTS_USER_TCC_DISABLE                                                 0x2453
#define mmCGTS_SM_CTRL_REG                                                      0x2454
#define mmSPI_LB_CU_MASK                                                        0x24d5
#define mmTA_CNTL_AUX                                                           0x2542
#define mmCB_PERFCOUNTER0_SELECT0                                               0x2688
#define mmCB_PERFCOUNTER0_SELECT1                                               0x2689
#define mmCB_PERFCOUNTER1_SELECT0                                               0x268a
#define mmCB_PERFCOUNTER1_SELECT1                                               0x268b
#define mmCB_PERFCOUNTER2_SELECT0                                               0x268c
#define mmCB_PERFCOUNTER2_SELECT1                                               0x268d
#define mmCB_PERFCOUNTER3_SELECT0                                               0x268e
#define mmCB_PERFCOUNTER3_SELECT1                                               0x268f
#define mmCB_CGTT_SCLK_CTRL                                                     0x2698
#define mmTCP_CHAN_STEER_LO                                                     0x2b03
#define mmTCP_CHAN_STEER_HI                                                     0x2b04
#define mmDB_RENDER_CONTROL                                                     0xa000
#define mmPACKET3_NOP                                                           0x4
#define mmPACKET3_WRITE_GDS_RAM                                                 0x7
#define mmPACKET3_SET_PREDICATION                                               0x8
#define mmPACKET3_DRAW_INDIRECT                                                 0x9
#define mmPACKET3_CONTEXT_CONTROL                                               0xa
#define mmPACKET3_DRAW_INDIRECT_MULTI                                           0xb
#define mmPACKET3_DRAW_INDEX_MULTI_AUTO                                         0xc
#define mmPACKET3_STRMOUT_BUFFER_UPDATE                                         0xd
#define mmPACKET3_DRAW_INDEX_INDIRECT_MULTI                                     0xe
#define mmPACKET3_WAIT_REG_MEM                                                  0xf
#define mmPACKET3_COPY_DATA                                                     0x10
#define mmPACKET3_ME_INITIALIZE                                                 0x11
#define mmPACKET3_EVENT_WRITE_EOS                                               0x12
#define mmPACKET3_LOAD_CONTEXT_REG                                              0x18
#define mmPACKET3_SET_CONFIG_REG                                                0x1a
#define mmPACKET3_SET_RESOURCE_INDIRECT                                         0x1d
#define mmPACKET3_LOAD_CONST_RAM                                                0x20
#define mmPACKET3_INCREMENT_CE_COUNTER                                          0x21
#define mmPACKET3_WAIT_ON_DE_COUNTER_DIFF                                       0x22
#define mmD1GRPH_PRIMARY_SURFACE_ADDRESS                                        0x1844
#define mmD1GRPH_SECONDARY_SURFACE_ADDRESS                                      0x1846
#define mmD2GRPH_PRIMARY_SURFACE_ADDRESS                                        0x1a44
#define mmD2GRPH_SECONDARY_SURFACE_ADDRESS                                      0x1a46

#endif /*__OTHER_SI_D_H__*/
