#ifndef __OTHER_SI_ENUM_H__
#define __OTHER_SI_ENUM_H__

typedef enum PACKET3_NOP {
	PACKET3_NOP__GDS_PARTITION_BASE                    = 2,
	PACKET3_NOP__CE_PARTITION_BASE                     = 3,
} PACKET3_NOP;
typedef enum PACKET3_SET_CONFIG_REG {
	PACKET3_SET_CONFIG_REG__PACKET3_SET_CONFIG_REG_START = 0x00008000,
	PACKET3_SET_CONFIG_REG__PACKET3_SET_CONFIG_REG_END = 0x0000b000,
	PACKET3_SET_CONFIG_REG__PACKET3_SET_CONTEXT_REG_START = 0x00028000,
	PACKET3_SET_CONFIG_REG__PACKET3_SET_CONTEXT_REG_END = 0x00029000,
} PACKET3_SET_CONFIG_REG;
typedef enum PACKET3_SET_RESOURCE_INDIRECT {
	PACKET3_SET_RESOURCE_INDIRECT__PACKET3_SET_SH_REG_START = 0x0000b000,
	PACKET3_SET_RESOURCE_INDIRECT__PACKET3_SET_SH_REG_END = 0x0000c000,
} PACKET3_SET_RESOURCE_INDIRECT;

#endif /*__OTHER_SI_ENUM_H__*/
