#ifndef __GFX_6_0_SH_MASK_H__
#define __GFX_6_0_SH_MASK_H__

#define GRBM_STATUS2__RLC_RQ_PENDING_MASK                                     0x00000001
#define GRBM_STATUS2__RLC_RQ_PENDING__SHIFT                                   0
#define GRBM_STATUS2__TC_BUSY_MASK                                            0x00000200
#define GRBM_STATUS2__TC_BUSY__SHIFT                                          9
#define GRBM_STATUS2__RLC_BUSY_MASK                                           0x00000100
#define GRBM_STATUS2__RLC_BUSY__SHIFT                                         8
#define GRBM_STATUS__CP_BUSY_MASK                                             0x20000000
#define GRBM_STATUS__CP_BUSY__SHIFT                                           29
#define GRBM_STATUS__CF_RQ_PENDING_MASK                                       0x00000080
#define GRBM_STATUS__CF_RQ_PENDING__SHIFT                                     7
#define GRBM_STATUS__SPI_BUSY_MASK                                            0x00400000
#define GRBM_STATUS__SPI_BUSY__SHIFT                                          22
#define GRBM_STATUS__RING2_RQ_PENDING_MASK                                    0x00000010
#define GRBM_STATUS__RING2_RQ_PENDING__SHIFT                                  4
#define GRBM_STATUS__IA_BUSY_MASK                                             0x00080000
#define GRBM_STATUS__IA_BUSY__SHIFT                                           19
#define GRBM_STATUS__GUI_ACTIVE_MASK                                          0x80000000
#define GRBM_STATUS__GUI_ACTIVE__SHIFT                                        31
#define GRBM_STATUS__PF_RQ_PENDING_MASK                                       0x00000100
#define GRBM_STATUS__PF_RQ_PENDING__SHIFT                                     8
#define GRBM_STATUS__GRBM_EE_BUSY_MASK                                        0x00000400
#define GRBM_STATUS__GRBM_EE_BUSY__SHIFT                                      10
#define GRBM_STATUS__PA_BUSY_MASK                                             0x02000000
#define GRBM_STATUS__PA_BUSY__SHIFT                                           25
#define GRBM_STATUS__VGT_BUSY_MASK                                            0x00020000
#define GRBM_STATUS__VGT_BUSY__SHIFT                                          17
#define GRBM_STATUS__SRBM_RQ_PENDING_MASK                                     0x00000020
#define GRBM_STATUS__SRBM_RQ_PENDING__SHIFT                                   5
#define GRBM_STATUS__CB_CLEAN_MASK                                            0x00002000
#define GRBM_STATUS__CB_CLEAN__SHIFT                                          13
#define GRBM_STATUS__IA_BUSY_NO_DMA_MASK                                      0x00040000
#define GRBM_STATUS__IA_BUSY_NO_DMA__SHIFT                                    18
#define GRBM_STATUS__GDS_BUSY_MASK                                            0x00008000
#define GRBM_STATUS__GDS_BUSY__SHIFT                                          15
#define GRBM_STATUS__GDS_DMA_RQ_PENDING_MASK                                  0x00000200
#define GRBM_STATUS__GDS_DMA_RQ_PENDING__SHIFT                                9
#define GRBM_STATUS__DB_BUSY_MASK                                             0x04000000
#define GRBM_STATUS__DB_BUSY__SHIFT                                           26
#define GRBM_STATUS__BCI_BUSY_MASK                                            0x00800000
#define GRBM_STATUS__BCI_BUSY__SHIFT                                          23
#define GRBM_STATUS__CP_COHERENCY_BUSY_MASK                                   0x10000000
#define GRBM_STATUS__CP_COHERENCY_BUSY__SHIFT                                 28
#define GRBM_STATUS__RING1_RQ_PENDING_MASK                                    0x00000040
#define GRBM_STATUS__RING1_RQ_PENDING__SHIFT                                  6
#define GRBM_STATUS__CB_BUSY_MASK                                             0x40000000
#define GRBM_STATUS__CB_BUSY__SHIFT                                           30
#define GRBM_STATUS__DB_CLEAN_MASK                                            0x00001000
#define GRBM_STATUS__DB_CLEAN__SHIFT                                          12
#define GRBM_STATUS__CMDFIFO_AVAIL_MASK                                       0x0000000F
#define GRBM_STATUS__CMDFIFO_AVAIL__SHIFT                                     0
#define GRBM_STATUS__TA_BUSY_MASK                                             0x00004000
#define GRBM_STATUS__TA_BUSY__SHIFT                                           14
#define GRBM_STATUS__SX_BUSY_MASK                                             0x00100000
#define GRBM_STATUS__SX_BUSY__SHIFT                                           20
#define GRBM_STATUS__SC_BUSY_MASK                                             0x01000000
#define GRBM_STATUS__SC_BUSY__SHIFT                                           24
#define GRBM_STATUS_SE1__SE_DB_BUSY_MASK                                      0x40000000
#define GRBM_STATUS_SE1__SE_DB_BUSY__SHIFT                                    30
#define GRBM_STATUS_SE1__SE_PA_BUSY_MASK                                      0x01000000
#define GRBM_STATUS_SE1__SE_PA_BUSY__SHIFT                                    24
#define GRBM_STATUS_SE1__SE_VGT_BUSY_MASK                                     0x00800000
#define GRBM_STATUS_SE1__SE_VGT_BUSY__SHIFT                                   23
#define GRBM_STATUS_SE1__SE_SX_BUSY_MASK                                      0x04000000
#define GRBM_STATUS_SE1__SE_SX_BUSY__SHIFT                                    26
#define GRBM_STATUS_SE1__SE_SC_BUSY_MASK                                      0x20000000
#define GRBM_STATUS_SE1__SE_SC_BUSY__SHIFT                                    29
#define GRBM_STATUS_SE1__SE_SPI_BUSY_MASK                                     0x08000000
#define GRBM_STATUS_SE1__SE_SPI_BUSY__SHIFT                                   27
#define GRBM_STATUS_SE1__SE_DB_CLEAN_MASK                                     0x00000002
#define GRBM_STATUS_SE1__SE_DB_CLEAN__SHIFT                                   1
#define GRBM_STATUS_SE1__SE_BCI_BUSY_MASK                                     0x00400000
#define GRBM_STATUS_SE1__SE_BCI_BUSY__SHIFT                                   22
#define GRBM_STATUS_SE1__SE_CB_BUSY_MASK                                      0x80000000
#define GRBM_STATUS_SE1__SE_CB_BUSY__SHIFT                                    31
#define GRBM_STATUS_SE1__SE_TA_BUSY_MASK                                      0x02000000
#define GRBM_STATUS_SE1__SE_TA_BUSY__SHIFT                                    25
#define GRBM_STATUS_SE1__SE_CB_CLEAN_MASK                                     0x00000004
#define GRBM_STATUS_SE1__SE_CB_CLEAN__SHIFT                                   2
#define GRBM_SOFT_RESET__SOFT_RESET_GDS_MASK                                  0x00000010
#define GRBM_SOFT_RESET__SOFT_RESET_GDS__SHIFT                                4
#define GRBM_SOFT_RESET__SOFT_RESET_DB_MASK                                   0x00000008
#define GRBM_SOFT_RESET__SOFT_RESET_DB__SHIFT                                 3
#define GRBM_SOFT_RESET__SOFT_RESET_CP_MASK                                   0x00000001
#define GRBM_SOFT_RESET__SOFT_RESET_CP__SHIFT                                 0
#define GRBM_SOFT_RESET__SOFT_RESET_VGT_MASK                                  0x00004000
#define GRBM_SOFT_RESET__SOFT_RESET_VGT__SHIFT                                14
#define GRBM_SOFT_RESET__SOFT_RESET_SPI_MASK                                  0x00000100
#define GRBM_SOFT_RESET__SOFT_RESET_SPI__SHIFT                                8
#define GRBM_SOFT_RESET__SOFT_RESET_TC_MASK                                   0x00000800
#define GRBM_SOFT_RESET__SOFT_RESET_TC__SHIFT                                 11
#define GRBM_SOFT_RESET__SOFT_RESET_PA_MASK                                   0x00000020
#define GRBM_SOFT_RESET__SOFT_RESET_PA__SHIFT                                 5
#define GRBM_SOFT_RESET__SOFT_RESET_RLC_MASK                                  0x00000004
#define GRBM_SOFT_RESET__SOFT_RESET_RLC__SHIFT                                2
#define GRBM_SOFT_RESET__SOFT_RESET_IA_MASK                                   0x00008000
#define GRBM_SOFT_RESET__SOFT_RESET_IA__SHIFT                                 15
#define GRBM_SOFT_RESET__SOFT_RESET_CB_MASK                                   0x00000002
#define GRBM_SOFT_RESET__SOFT_RESET_CB__SHIFT                                 1
#define GRBM_SOFT_RESET__SOFT_RESET_TA_MASK                                   0x00001000
#define GRBM_SOFT_RESET__SOFT_RESET_TA__SHIFT                                 12
#define GRBM_SOFT_RESET__SOFT_RESET_SC_MASK                                   0x00000040
#define GRBM_SOFT_RESET__SOFT_RESET_SC__SHIFT                                 6
#define GRBM_SOFT_RESET__SOFT_RESET_BCI_MASK                                  0x00000080
#define GRBM_SOFT_RESET__SOFT_RESET_BCI__SHIFT                                7
#define GRBM_SOFT_RESET__SOFT_RESET_SX_MASK                                   0x00000400
#define GRBM_SOFT_RESET__SOFT_RESET_SX__SHIFT                                 10
#define GRBM_GFX_INDEX__SE_BROADCAST_WRITES_MASK                              0x80000000
#define GRBM_GFX_INDEX__SE_BROADCAST_WRITES__SHIFT                            31
#define GRBM_GFX_INDEX__SE_INDEX_MASK                                         (0xFF << 16)
#define GRBM_GFX_INDEX__SE_INDEX__SHIFT                                       16
#define GRBM_GFX_INDEX__INSTANCE_INDEX_MASK                                   0xFF
#define GRBM_GFX_INDEX__INSTANCE_INDEX__SHIFT                                 0
#define GRBM_GFX_INDEX__SH_INDEX_MASK                                         (0xFF << 8)
#define GRBM_GFX_INDEX__SH_INDEX__SHIFT                                       8
#define GRBM_GFX_INDEX__INSTANCE_BROADCAST_WRITES_MASK                        0x40000000
#define GRBM_GFX_INDEX__INSTANCE_BROADCAST_WRITES__SHIFT                      30
#define GRBM_GFX_INDEX__SH_BROADCAST_WRITES_MASK                              0x20000000
#define GRBM_GFX_INDEX__SH_BROADCAST_WRITES__SHIFT                            29
#define GRBM_INT_CNTL__RDERR_INT_ENABLE_MASK                                  0x00000001
#define GRBM_INT_CNTL__RDERR_INT_ENABLE__SHIFT                                0
#define GRBM_INT_CNTL__GUI_IDLE_INT_ENABLE_MASK                               0x00080000
#define GRBM_INT_CNTL__GUI_IDLE_INT_ENABLE__SHIFT                             19
#define CP_ME_CNTL__CP_CE_HALT_MASK                                           0x01000000
#define CP_ME_CNTL__CP_CE_HALT__SHIFT                                         24
#define CP_ME_CNTL__CP_ME_HALT_MASK                                           0x10000000
#define CP_ME_CNTL__CP_ME_HALT__SHIFT                                         28
#define CP_ME_CNTL__CP_PFP_HALT_MASK                                          0x04000000
#define CP_ME_CNTL__CP_PFP_HALT__SHIFT                                        26
#define CP_QUEUE_THRESHOLDS__ROQ_IB1_START_MASK                               (0x3f << 0)
#define CP_QUEUE_THRESHOLDS__ROQ_IB1_START__SHIFT                             0
#define CP_QUEUE_THRESHOLDS__ROQ_IB2_START_MASK                               (0x3f << 8)
#define CP_QUEUE_THRESHOLDS__ROQ_IB2_START__SHIFT                             8
#define CP_MEQ_THRESHOLDS__MEQ2_START_MASK                                    (0xff << 8)
#define CP_MEQ_THRESHOLDS__MEQ2_START__SHIFT                                  8
#define CP_MEQ_THRESHOLDS__MEQ1_START_MASK                                    (0xff << 0)
#define CP_MEQ_THRESHOLDS__MEQ1_START__SHIFT                                  0
#define VGT_CACHE_INVALIDATION__AUTO_INVLD_EN_MASK                            0xc0
#define VGT_CACHE_INVALIDATION__AUTO_INVLD_EN__SHIFT                          6
#define VGT_CACHE_INVALIDATION__CACHE_INVALIDATION_MASK                       3
#define VGT_CACHE_INVALIDATION__CACHE_INVALIDATION__SHIFT                     0
#define CC_GC_SHADER_ARRAY_CONFIG__INACTIVE_CUS_MASK                          0xFFFF0000
#define CC_GC_SHADER_ARRAY_CONFIG__INACTIVE_CUS__SHIFT                        16
#define PA_CL_ENHANCE__NUM_CLIP_SEQ_MASK                                      0x6
#define PA_CL_ENHANCE__NUM_CLIP_SEQ__SHIFT                                    1
#define PA_CL_ENHANCE__CLIP_VTX_REORDER_ENA_MASK                              0x00000001
#define PA_CL_ENHANCE__CLIP_VTX_REORDER_ENA__SHIFT                            0
#define PA_SC_FORCE_EOV_MAX_CNTS__FORCE_EOV_MAX_REZ_CNT_MASK                  (0xffff << 16)
#define PA_SC_FORCE_EOV_MAX_CNTS__FORCE_EOV_MAX_REZ_CNT__SHIFT                16
#define PA_SC_FORCE_EOV_MAX_CNTS__FORCE_EOV_MAX_CLK_CNT_MASK                  0xffff
#define PA_SC_FORCE_EOV_MAX_CNTS__FORCE_EOV_MAX_CLK_CNT__SHIFT                0
#define PA_SC_FIFO_SIZE__SC_BACKEND_PRIM_FIFO_SIZE_MASK                       0x7fc0
#define PA_SC_FIFO_SIZE__SC_BACKEND_PRIM_FIFO_SIZE__SHIFT                     6
#define PA_SC_FIFO_SIZE__SC_FRONTEND_PRIM_FIFO_SIZE_MASK                      (0x3f << 0)
#define PA_SC_FIFO_SIZE__SC_FRONTEND_PRIM_FIFO_SIZE__SHIFT                    0
#define PA_SC_FIFO_SIZE__SC_EARLYZ_TILE_FIFO_SIZE_MASK                        0xff800000
#define PA_SC_FIFO_SIZE__SC_EARLYZ_TILE_FIFO_SIZE__SHIFT                      23
#define PA_SC_FIFO_SIZE__SC_HIZ_TILE_FIFO_SIZE_MASK                           0x1f8000
#define PA_SC_FIFO_SIZE__SC_HIZ_TILE_FIFO_SIZE__SHIFT                         15
#define SQ_POWER_THROTTLE__MAX_POWER_MASK                                     (0x3fff << 16)
#define SQ_POWER_THROTTLE__MAX_POWER__SHIFT                                   0
#define SQ_POWER_THROTTLE__MIN_POWER_MASK                                     (0x3fff << 0)
#define SQ_POWER_THROTTLE__MIN_POWER__SHIFT                                   0
#define SQ_POWER_THROTTLE2__MAX_POWER_DELTA_MASK                              (0x3fff << 0)
#define SQ_POWER_THROTTLE2__MAX_POWER_DELTA__SHIFT                            0
#define SQ_POWER_THROTTLE2__STI_SIZE_MASK                                     (0x3ff << 16)
#define SQ_POWER_THROTTLE2__STI_SIZE__SHIFT                                   16
#define SQ_POWER_THROTTLE2__LTI_RATIO_MASK                                    (0xf << 27)
#define SQ_POWER_THROTTLE2__LTI_RATIO__SHIFT                                  27
#define SPI_CONFIG_CNTL_1__INTERP_ONE_PRIM_PER_ROW_MASK                       0x00000010
#define SPI_CONFIG_CNTL_1__INTERP_ONE_PRIM_PER_ROW__SHIFT                     4
#define SPI_CONFIG_CNTL_1__VTX_DONE_DELAY_MASK                                (0xf << 0)
#define SPI_CONFIG_CNTL_1__VTX_DONE_DELAY__SHIFT                              0
#define CGTS_USER_TCC_DISABLE__TCC_DISABLE_MASK                               0xFFFF0000
#define CGTS_USER_TCC_DISABLE__TCC_DISABLE__SHIFT                             16
#define CGTS_SM_CTRL_REG__OVERRIDE_MASK                                       0x00200000
#define CGTS_SM_CTRL_REG__OVERRIDE__SHIFT                                     21
#define CGTS_SM_CTRL_REG__LS_OVERRIDE_MASK                                    0x00400000
#define CGTS_SM_CTRL_REG__LS_OVERRIDE__SHIFT                                  22
#define GB_ADDR_CONFIG__NUM_SHADER_ENGINES_MASK                               0x00003000
#define GB_ADDR_CONFIG__NUM_SHADER_ENGINES__SHIFT                             12
#define GB_ADDR_CONFIG__SHADER_ENGINE_TILE_SIZE_MASK                          0x00070000
#define GB_ADDR_CONFIG__SHADER_ENGINE_TILE_SIZE__SHIFT                        16
#define GB_ADDR_CONFIG__NUM_GPUS_MASK                                         0x00700000
#define GB_ADDR_CONFIG__NUM_GPUS__SHIFT                                       20
#define GB_ADDR_CONFIG__NUM_PIPES_MASK                                        0x00000007
#define GB_ADDR_CONFIG__NUM_PIPES__SHIFT                                      0
#define GB_ADDR_CONFIG__PIPE_INTERLEAVE_SIZE_MASK                             0x00000070
#define GB_ADDR_CONFIG__PIPE_INTERLEAVE_SIZE__SHIFT                           4
#define GB_ADDR_CONFIG__MULTI_GPU_TILE_SIZE_MASK                              0x03000000
#define GB_ADDR_CONFIG__MULTI_GPU_TILE_SIZE__SHIFT                            24
#define GB_ADDR_CONFIG__ROW_SIZE_MASK                                         0x30000000
#define GB_ADDR_CONFIG__ROW_SIZE__SHIFT                                       28
#define GC_USER_RB_BACKEND_DISABLE__BACKEND_DISABLE_MASK                      0x00FF0000
#define GC_USER_RB_BACKEND_DISABLE__BACKEND_DISABLE__SHIFT                    16
#define CP_RB0_CNTL__RB_RPTR_WR_ENA_MASK                                      0x80000000
#define CP_RB0_CNTL__RB_RPTR_WR_ENA__SHIFT                                    31
#define CP_RB0_CNTL__RB_NO_UPDATE_MASK                                        0x08000000
#define CP_RB0_CNTL__RB_NO_UPDATE__SHIFT                                      27
#define CP_RB0_CNTL__BUF_SWAP_32BIT_MASK                                      0x00020000
#define CP_RB0_CNTL__BUF_SWAP_32BIT__SHIFT                                    16
#define CP_INT_CNTL_RING2__CP_RINGID1_INT_ENABLE_MASK                         0x40000000
#define CP_INT_CNTL_RING2__CP_RINGID1_INT_ENABLE__SHIFT                       30
#define CP_INT_CNTL_RING2__CNTX_EMPTY_INT_ENABLE_MASK                         0x00100000
#define CP_INT_CNTL_RING2__CNTX_EMPTY_INT_ENABLE__SHIFT                       20
#define CP_INT_CNTL_RING2__WAIT_MEM_SEM_INT_ENABLE_MASK                       0x00200000
#define CP_INT_CNTL_RING2__WAIT_MEM_SEM_INT_ENABLE__SHIFT                     21
#define CP_INT_CNTL_RING2__CP_RINGID0_INT_ENABLE_MASK                         0x80000000
#define CP_INT_CNTL_RING2__CP_RINGID0_INT_ENABLE__SHIFT                       31
#define CP_INT_CNTL_RING2__CNTX_BUSY_INT_ENABLE_MASK                          0x00080000
#define CP_INT_CNTL_RING2__CNTX_BUSY_INT_ENABLE__SHIFT                        19
#define CP_INT_CNTL_RING2__CP_RINGID2_INT_ENABLE_MASK                         0x20000000
#define CP_INT_CNTL_RING2__CP_RINGID2_INT_ENABLE__SHIFT                       29
#define CP_INT_CNTL_RING2__TIME_STAMP_INT_ENABLE_MASK                         0x04000000
#define CP_INT_CNTL_RING2__TIME_STAMP_INT_ENABLE__SHIFT                       26
#define CP_INT_STATUS_RING2__WAIT_MEM_SEM_INT_STAT_MASK                       0x00200000
#define CP_INT_STATUS_RING2__WAIT_MEM_SEM_INT_STAT__SHIFT                     21
#define CP_INT_STATUS_RING2__CP_RINGID1_INT_STAT_MASK                         0x40000000
#define CP_INT_STATUS_RING2__CP_RINGID1_INT_STAT__SHIFT                       30
#define CP_INT_STATUS_RING2__CP_RINGID2_INT_STAT_MASK                         0x20000000
#define CP_INT_STATUS_RING2__CP_RINGID2_INT_STAT__SHIFT                       29
#define CP_INT_STATUS_RING2__CP_RINGID0_INT_STAT_MASK                         0x80000000
#define CP_INT_STATUS_RING2__CP_RINGID0_INT_STAT__SHIFT                       31
#define CP_INT_STATUS_RING2__TIME_STAMP_INT_STAT_MASK                         0x04000000
#define CP_INT_STATUS_RING2__TIME_STAMP_INT_STAT__SHIFT                       26
#define CP_MEM_SLP_CNTL__CP_MEM_LS_EN_MASK                                    0x00000001
#define CP_MEM_SLP_CNTL__CP_MEM_LS_EN__SHIFT                                  0
#define RLC_CNTL__RLC_ENABLE_MASK                                             0x00000001
#define RLC_CNTL__RLC_ENABLE__SHIFT                                           0
#define RLC_LB_CNTL__LOAD_BALANCE_ENABLE_MASK                                 0x00000001
#define RLC_LB_CNTL__LOAD_BALANCE_ENABLE__SHIFT                               0
#define RLC_STAT__GFX_POWER_STATUS_MASK                                       0x00000002
#define RLC_STAT__GFX_POWER_STATUS__SHIFT                                     1
#define RLC_STAT__GFX_LS_STATUS_MASK                                          0x00000008
#define RLC_STAT__GFX_LS_STATUS__SHIFT                                        3
#define RLC_STAT__GFX_CLOCK_STATUS_MASK                                       0x00000004
#define RLC_STAT__GFX_CLOCK_STATUS__SHIFT                                     2
#define RLC_STAT__RLC_BUSY_STATUS_MASK                                        0x00000001
#define RLC_STAT__RLC_BUSY_STATUS__SHIFT                                      0
#define RLC_PG_CNTL__GFX_PG_SRC_MASK                                          0x00000002
#define RLC_PG_CNTL__GFX_PG_SRC__SHIFT                                        1
#define RLC_PG_CNTL__GFX_PG_ENABLE_MASK                                       0x00000001
#define RLC_PG_CNTL__GFX_PG_ENABLE__SHIFT                                     0
#define RLC_CGCG_CGLS_CTRL__CGLS_EN_MASK                                      0x00000002
#define RLC_CGCG_CGLS_CTRL__CGLS_EN__SHIFT                                    1
#define RLC_CGCG_CGLS_CTRL__CGCG_EN_MASK                                      0x00000001
#define RLC_CGCG_CGLS_CTRL__CGCG_EN__SHIFT                                    0
#define RLC_TTOP_D__RLC_TTPD_MASK                                             (0xff << 16)
#define RLC_TTOP_D__RLC_TTPD__SHIFT                                           16
#define RLC_TTOP_D__RLC_MSD_MASK                                              (0xff << 24)
#define RLC_TTOP_D__RLC_MSD__SHIFT                                            24
#define RLC_TTOP_D__RLC_PUD_MASK                                              (0xff << 0)
#define RLC_TTOP_D__RLC_PUD__SHIFT                                            0
#define RLC_TTOP_D__RLC_PDD_MASK                                              (0xff << 8)
#define RLC_TTOP_D__RLC_PDD__SHIFT                                            8
#define RLC_MAX_PG_CU__MAX_PU_CU_MASK                                         (0xff << 0)
#define RLC_MAX_PG_CU__MAX_PU_CU__SHIFT                                       0
#define RLC_AUTO_PG_CTRL__GRBM_REG_SGIT_MASK                                  (0xffff << 3)
#define RLC_AUTO_PG_CTRL__GRBM_REG_SGIT__SHIFT                                3
#define RLC_AUTO_PG_CTRL__AUTO_PG_EN_MASK                                     0x00000001
#define RLC_AUTO_PG_CTRL__AUTO_PG_EN__SHIFT                                   0
#define RLC_AUTO_PG_CTRL__PG_AFTER_GRBM_REG_ST_MASK                           (0x1fff << 19)
#define RLC_AUTO_PG_CTRL__PG_AFTER_GRBM_REG_ST__SHIFT                         19
#define VGT_EVENT_INITIATOR__THREAD_TRACE_START_MASK                          0x00000033
#define VGT_EVENT_INITIATOR__THREAD_TRACE_START__SHIFT                        0
#define VGT_EVENT_INITIATOR__CS_PARTIAL_FLUSH_MASK                            0x00000007
#define VGT_EVENT_INITIATOR__CS_PARTIAL_FLUSH__SHIFT                          0
#define VGT_EVENT_INITIATOR__THREAD_TRACE_FLUSH_MASK                          0x00000036
#define VGT_EVENT_INITIATOR__THREAD_TRACE_FLUSH__SHIFT                        0
#define VGT_EVENT_INITIATOR__DB_CACHE_FLUSH_AND_INV_MASK                      0x0000002a
#define VGT_EVENT_INITIATOR__DB_CACHE_FLUSH_AND_INV__SHIFT                    0
#define VGT_EVENT_INITIATOR__THREAD_TRACE_FINISH_MASK                         0x00000037
#define VGT_EVENT_INITIATOR__THREAD_TRACE_FINISH__SHIFT                       0
#define VGT_EVENT_INITIATOR__FLUSH_AND_INV_DB_DATA_TS_MASK                    0x0000002b
#define VGT_EVENT_INITIATOR__FLUSH_AND_INV_DB_DATA_TS__SHIFT                  0
#define VGT_EVENT_INITIATOR__CS_DONE_MASK                                     0x0000002f
#define VGT_EVENT_INITIATOR__CS_DONE__SHIFT                                   0
#define VGT_EVENT_INITIATOR__FLUSH_AND_INV_CB_META_MASK                       0x0000002e
#define VGT_EVENT_INITIATOR__FLUSH_AND_INV_CB_META__SHIFT                     0
#define VGT_EVENT_INITIATOR__PERFCOUNTER_START_MASK                           0x00000017
#define VGT_EVENT_INITIATOR__PERFCOUNTER_START__SHIFT                         0
#define VGT_EVENT_INITIATOR__CACHE_FLUSH_AND_INV_TS_EVENT_MASK                0x00000014
#define VGT_EVENT_INITIATOR__CACHE_FLUSH_AND_INV_TS_EVENT__SHIFT              0
#define VGT_EVENT_INITIATOR__VGT_FLUSH_MASK                                   0x00000024
#define VGT_EVENT_INITIATOR__VGT_FLUSH__SHIFT                                 0
#define VGT_EVENT_INITIATOR__PERFCOUNTER_SAMPLE_MASK                          0x0000001b
#define VGT_EVENT_INITIATOR__PERFCOUNTER_SAMPLE__SHIFT                        0
#define VGT_EVENT_INITIATOR__PS_DONE_MASK                                     0x00000030
#define VGT_EVENT_INITIATOR__PS_DONE__SHIFT                                   0
#define VGT_EVENT_INITIATOR__SAMPLE_STREAMOUTSTATS_MASK                       0x00000020
#define VGT_EVENT_INITIATOR__SAMPLE_STREAMOUTSTATS__SHIFT                     0
#define VGT_EVENT_INITIATOR__PIPELINESTAT_START_MASK                          0x00000019
#define VGT_EVENT_INITIATOR__PIPELINESTAT_START__SHIFT                        0
#define VGT_EVENT_INITIATOR__FLUSH_AND_INV_DB_META_MASK                       0x0000002c
#define VGT_EVENT_INITIATOR__FLUSH_AND_INV_DB_META__SHIFT                     0
#define VGT_EVENT_INITIATOR__VGT_STREAMOUT_RESET_MASK                         0x0000000a
#define VGT_EVENT_INITIATOR__VGT_STREAMOUT_RESET__SHIFT                       0
#define VGT_EVENT_INITIATOR__PS_PARTIAL_FLUSH_MASK                            0x00000010
#define VGT_EVENT_INITIATOR__PS_PARTIAL_FLUSH__SHIFT                          0
#define VGT_EVENT_INITIATOR__FLUSH_AND_INV_CB_PIXEL_DATA_MASK                 0x00000031
#define VGT_EVENT_INITIATOR__FLUSH_AND_INV_CB_PIXEL_DATA__SHIFT               0
#define VGT_EVENT_INITIATOR__VS_PARTIAL_FLUSH_MASK                            0x0000000f
#define VGT_EVENT_INITIATOR__VS_PARTIAL_FLUSH__SHIFT                          0
#define VGT_EVENT_INITIATOR__SAMPLE_PIPELINESTAT_MASK                         0x0000001e
#define VGT_EVENT_INITIATOR__SAMPLE_PIPELINESTAT__SHIFT                       0
#define VGT_EVENT_INITIATOR__CACHE_FLUSH_AND_INV_EVENT_MASK                   0x00000016
#define VGT_EVENT_INITIATOR__CACHE_FLUSH_AND_INV_EVENT__SHIFT                 0
#define VGT_EVENT_INITIATOR__CACHE_FLUSH_TS_MASK                              0x00000004
#define VGT_EVENT_INITIATOR__CACHE_FLUSH_TS__SHIFT                            0
#define VGT_EVENT_INITIATOR__THREAD_TRACE_STOP_MASK                           0x00000034
#define VGT_EVENT_INITIATOR__THREAD_TRACE_STOP__SHIFT                         0
#define VGT_EVENT_INITIATOR__PERFCOUNTER_STOP_MASK                            0x00000018
#define VGT_EVENT_INITIATOR__PERFCOUNTER_STOP__SHIFT                          0
#define VGT_EVENT_INITIATOR__RESET_VTX_CNT_MASK                               0x00000021
#define VGT_EVENT_INITIATOR__RESET_VTX_CNT__SHIFT                             0
#define VGT_EVENT_INITIATOR__FLUSH_AND_INV_CB_DATA_TS_MASK                    0x0000002d
#define VGT_EVENT_INITIATOR__FLUSH_AND_INV_CB_DATA_TS__SHIFT                  0
#define VGT_EVENT_INITIATOR__PIPELINESTAT_STOP_MASK                           0x0000001a
#define VGT_EVENT_INITIATOR__PIPELINESTAT_STOP__SHIFT                         0
#define VGT_EVENT_INITIATOR__CACHE_FLUSH_MASK                                 0x00000006
#define VGT_EVENT_INITIATOR__CACHE_FLUSH__SHIFT                               0
#define VGT_EVENT_INITIATOR__END_OF_PIPE_INCR_DE_MASK                         0x0000000b
#define VGT_EVENT_INITIATOR__END_OF_PIPE_INCR_DE__SHIFT                       0
#define VGT_EVENT_INITIATOR__RST_PIX_CNT_MASK                                 0x0000000d
#define VGT_EVENT_INITIATOR__RST_PIX_CNT__SHIFT                               0
#define VGT_EVENT_INITIATOR__BOTTOM_OF_PIPE_TS_MASK                           0x00000028
#define VGT_EVENT_INITIATOR__BOTTOM_OF_PIPE_TS__SHIFT                         0
#define VGT_EVENT_INITIATOR__ZPASS_DONE_MASK                                  0x00000015
#define VGT_EVENT_INITIATOR__ZPASS_DONE__SHIFT                                0
#define VGT_EVENT_INITIATOR__END_OF_PIPE_IB_END_MASK                          0x0000000c
#define VGT_EVENT_INITIATOR__END_OF_PIPE_IB_END__SHIFT                        0
#define VGT_EVENT_INITIATOR__SAMPLE_STREAMOUTSTATS2_MASK                      0x00000002
#define VGT_EVENT_INITIATOR__SAMPLE_STREAMOUTSTATS2__SHIFT                    0
#define VGT_EVENT_INITIATOR__SAMPLE_STREAMOUTSTATS3_MASK                      0x00000003
#define VGT_EVENT_INITIATOR__SAMPLE_STREAMOUTSTATS3__SHIFT                    0
#define VGT_EVENT_INITIATOR__SAMPLE_STREAMOUTSTATS1_MASK                      0x00000001
#define VGT_EVENT_INITIATOR__SAMPLE_STREAMOUTSTATS1__SHIFT                    0

#endif /*__GFX_6_0_SH_MASK_H__*/
