#ifndef __GMC_6_0_SH_MASK_H__
#define __GMC_6_0_SH_MASK_H__

#define VM_L2_CNTL__ENABLE_L2_PDE0_CACHE_LRU_UPDATE_BY_WRITE_MASK             0x00000400
#define VM_L2_CNTL__ENABLE_L2_PDE0_CACHE_LRU_UPDATE_BY_WRITE__SHIFT           10
#define VM_L2_CNTL__ENABLE_L2_CACHE_MASK                                      0x00000001
#define VM_L2_CNTL__ENABLE_L2_CACHE__SHIFT                                    0
#define VM_L2_CNTL__EFFECTIVE_L2_QUEUE_SIZE_MASK                              (7 << 15)
#define VM_L2_CNTL__EFFECTIVE_L2_QUEUE_SIZE__SHIFT                            15
#define VM_L2_CNTL__ENABLE_L2_FRAGMENT_PROCESSING_MASK                        0x00000002
#define VM_L2_CNTL__ENABLE_L2_FRAGMENT_PROCESSING__SHIFT                      1
#define VM_L2_CNTL__ENABLE_L2_PTE_CACHE_LRU_UPDATE_BY_WRITE_MASK              0x00000200
#define VM_L2_CNTL__ENABLE_L2_PTE_CACHE_LRU_UPDATE_BY_WRITE__SHIFT            9
#define VM_L2_CNTL__CONTEXT1_IDENTITY_ACCESS_MODE_MASK                        (3 << 19)
#define VM_L2_CNTL__CONTEXT1_IDENTITY_ACCESS_MODE__SHIFT                      19
#define VM_L2_CNTL2__INVALIDATE_L2_CACHE_MASK                                 0x00000002
#define VM_L2_CNTL2__INVALIDATE_L2_CACHE__SHIFT                               1
#define VM_L2_CNTL2__INVALIDATE_ALL_L1_TLBS_MASK                              0x00000001
#define VM_L2_CNTL2__INVALIDATE_ALL_L1_TLBS__SHIFT                            0
#define VM_L2_CNTL3__L2_CACHE_BIGK_ASSOCIATIVITY_MASK                         0x00100000
#define VM_L2_CNTL3__L2_CACHE_BIGK_ASSOCIATIVITY__SHIFT                       20
#define VM_L2_CNTL3__BANK_SELECT_MASK                                         (0xf << 0)
#define VM_L2_CNTL3__BANK_SELECT__SHIFT                                       0
#define VM_L2_CNTL3__L2_CACHE_BIGK_FRAGMENT_SIZE_MASK                         (0xf << 15)
#define VM_L2_CNTL3__L2_CACHE_BIGK_FRAGMENT_SIZE__SHIFT                       15
#define VM_L2_STATUS__L2_BUSY_MASK                                            0x00000001
#define VM_L2_STATUS__L2_BUSY__SHIFT                                          0
#define VM_CONTEXT0_CNTL__VALID_PROTECTION_FAULT_ENABLE_INTERRUPT_MASK        0x00001000
#define VM_CONTEXT0_CNTL__VALID_PROTECTION_FAULT_ENABLE_INTERRUPT__SHIFT      12
#define VM_CONTEXT0_CNTL__PAGE_TABLE_BLOCK_SIZE_MASK                          (0xF << 24)
#define VM_CONTEXT0_CNTL__PAGE_TABLE_BLOCK_SIZE__SHIFT                        24
#define VM_CONTEXT0_CNTL__READ_PROTECTION_FAULT_ENABLE_INTERRUPT_MASK         0x00008000
#define VM_CONTEXT0_CNTL__READ_PROTECTION_FAULT_ENABLE_INTERRUPT__SHIFT       15
#define VM_CONTEXT0_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT_MASK           0x00000400
#define VM_CONTEXT0_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT         10
#define VM_CONTEXT0_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK     0x00000080
#define VM_CONTEXT0_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT   7
#define VM_CONTEXT0_CNTL__ENABLE_CONTEXT_MASK                                 0x00000001
#define VM_CONTEXT0_CNTL__ENABLE_CONTEXT__SHIFT                               0
#define VM_CONTEXT0_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_INTERRUPT_MASK   0x00000040
#define VM_CONTEXT0_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_INTERRUPT__SHIFT 6
#define VM_CONTEXT0_CNTL__PAGE_TABLE_DEPTH_MASK                               (3 << 1)
#define VM_CONTEXT0_CNTL__PAGE_TABLE_DEPTH__SHIFT                             1
#define VM_CONTEXT0_CNTL__RANGE_PROTECTION_FAULT_ENABLE_INTERRUPT_MASK        0x00000008
#define VM_CONTEXT0_CNTL__RANGE_PROTECTION_FAULT_ENABLE_INTERRUPT__SHIFT      3
#define VM_CONTEXT0_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          0x00080000
#define VM_CONTEXT0_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        19
#define VM_CONTEXT0_CNTL__PDE0_PROTECTION_FAULT_ENABLE_INTERRUPT_MASK         0x00000200
#define VM_CONTEXT0_CNTL__PDE0_PROTECTION_FAULT_ENABLE_INTERRUPT__SHIFT       9
#define VM_CONTEXT0_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT_MASK           0x00010000
#define VM_CONTEXT0_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT         16
#define VM_CONTEXT0_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          0x00002000
#define VM_CONTEXT0_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        13
#define VM_CONTEXT0_CNTL__WRITE_PROTECTION_FAULT_ENABLE_INTERRUPT_MASK        0x00040000
#define VM_CONTEXT0_CNTL__WRITE_PROTECTION_FAULT_ENABLE_INTERRUPT__SHIFT      18
#define VM_CONTEXT0_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          0x00000010
#define VM_CONTEXT0_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        4
#define VM_CONTEXT1_CNTL__VALID_PROTECTION_FAULT_ENABLE_INTERRUPT_MASK        0x00001000
#define VM_CONTEXT1_CNTL__VALID_PROTECTION_FAULT_ENABLE_INTERRUPT__SHIFT      12
#define VM_CONTEXT1_CNTL__PAGE_TABLE_BLOCK_SIZE_MASK                          (0xF << 24)
#define VM_CONTEXT1_CNTL__PAGE_TABLE_BLOCK_SIZE__SHIFT                        24
#define VM_CONTEXT1_CNTL__READ_PROTECTION_FAULT_ENABLE_INTERRUPT_MASK         0x00008000
#define VM_CONTEXT1_CNTL__READ_PROTECTION_FAULT_ENABLE_INTERRUPT__SHIFT       15
#define VM_CONTEXT1_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT_MASK           0x00000400
#define VM_CONTEXT1_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT         10
#define VM_CONTEXT1_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK     0x00000080
#define VM_CONTEXT1_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT   7
#define VM_CONTEXT1_CNTL__ENABLE_CONTEXT_MASK                                 0x00000001
#define VM_CONTEXT1_CNTL__ENABLE_CONTEXT__SHIFT                               0
#define VM_CONTEXT1_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_INTERRUPT_MASK   0x00000040
#define VM_CONTEXT1_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_INTERRUPT__SHIFT 6
#define VM_CONTEXT1_CNTL__PAGE_TABLE_DEPTH_MASK                               (3 << 1)
#define VM_CONTEXT1_CNTL__PAGE_TABLE_DEPTH__SHIFT                             1
#define VM_CONTEXT1_CNTL__RANGE_PROTECTION_FAULT_ENABLE_INTERRUPT_MASK        0x00000008
#define VM_CONTEXT1_CNTL__RANGE_PROTECTION_FAULT_ENABLE_INTERRUPT__SHIFT      3
#define VM_CONTEXT1_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          0x00080000
#define VM_CONTEXT1_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        19
#define VM_CONTEXT1_CNTL__PDE0_PROTECTION_FAULT_ENABLE_INTERRUPT_MASK         0x00000200
#define VM_CONTEXT1_CNTL__PDE0_PROTECTION_FAULT_ENABLE_INTERRUPT__SHIFT       9
#define VM_CONTEXT1_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT_MASK           0x00010000
#define VM_CONTEXT1_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT         16
#define VM_CONTEXT1_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          0x00002000
#define VM_CONTEXT1_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        13
#define VM_CONTEXT1_CNTL__WRITE_PROTECTION_FAULT_ENABLE_INTERRUPT_MASK        0x00040000
#define VM_CONTEXT1_CNTL__WRITE_PROTECTION_FAULT_ENABLE_INTERRUPT__SHIFT      18
#define VM_CONTEXT1_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          0x00000010
#define VM_CONTEXT1_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        4
#define VM_CONTEXT1_PROTECTION_FAULT_STATUS__MEMORY_CLIENT_ID_MASK            (0xff << 12)
#define VM_CONTEXT1_PROTECTION_FAULT_STATUS__MEMORY_CLIENT_ID__SHIFT          12
#define VM_CONTEXT1_PROTECTION_FAULT_STATUS__PROTECTIONS_MASK                 (0xf << 0)
#define VM_CONTEXT1_PROTECTION_FAULT_STATUS__PROTECTIONS__SHIFT               0
#define VM_CONTEXT1_PROTECTION_FAULT_STATUS__MEMORY_CLIENT_RW_MASK            (1 << 24)
#define VM_CONTEXT1_PROTECTION_FAULT_STATUS__MEMORY_CLIENT_RW__SHIFT          24
#define VM_CONTEXT1_PROTECTION_FAULT_STATUS__FAULT_VMID_MASK                  (0xf << 25)
#define VM_CONTEXT1_PROTECTION_FAULT_STATUS__FAULT_VMID__SHIFT                25
#define VM_L2_CG__MC_LS_ENABLE_MASK                                           0x00080000
#define VM_L2_CG__MC_LS_ENABLE__SHIFT                                         19
#define VM_L2_CG__MC_CG_ENABLE_MASK                                           0x00040000
#define VM_L2_CG__MC_CG_ENABLE__SHIFT                                         18
#define MC_SHARED_CHMAP__NOOFCHAN_MASK                                        0x0000f000
#define MC_SHARED_CHMAP__NOOFCHAN__SHIFT                                      12
#define MC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE_MASK                         (3 << 3)
#define MC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE__SHIFT                       3
#define MC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE_NOT_IN_SYS_MASK              0x00000018
#define MC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE_NOT_IN_SYS__SHIFT            3
#define MC_VM_MX_L1_TLB_CNTL__SYSTEM_APERTURE_UNMAPPED_ACCESS_PASS_THRU_MASK  0x00000000
#define MC_VM_MX_L1_TLB_CNTL__SYSTEM_APERTURE_UNMAPPED_ACCESS_PASS_THRU__SHIFT 5
#define MC_VM_MX_L1_TLB_CNTL__ENABLE_ADVANCED_DRIVER_MODEL_MASK               0x00000040
#define MC_VM_MX_L1_TLB_CNTL__ENABLE_ADVANCED_DRIVER_MODEL__SHIFT             6
#define MC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE_PA_ONLY_MASK                 0x00000000
#define MC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE_PA_ONLY__SHIFT               3
#define MC_VM_MX_L1_TLB_CNTL__ENABLE_L1_FRAGMENT_PROCESSING_MASK              0x00000002
#define MC_VM_MX_L1_TLB_CNTL__ENABLE_L1_FRAGMENT_PROCESSING__SHIFT            1
#define MC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE_USE_SYS_MAP_MASK             0x00000008
#define MC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE_USE_SYS_MAP__SHIFT           3
#define MC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE_IN_SYS_MASK                  0x00000010
#define MC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE_IN_SYS__SHIFT                3
#define MC_VM_MX_L1_TLB_CNTL__ENABLE_L1_TLB_MASK                              0x00000001
#define MC_VM_MX_L1_TLB_CNTL__ENABLE_L1_TLB__SHIFT                            0
#define MC_SHARED_BLACKOUT_CNTL__BLACKOUT_MODE_MASK                           (0x7 << 0)
#define MC_SHARED_BLACKOUT_CNTL__BLACKOUT_MODE__SHIFT                         0
#define MC_ARB_RAMCFG__NOOFRANK_MASK                                          0x00000004
#define MC_ARB_RAMCFG__NOOFRANK__SHIFT                                        2
#define MC_ARB_RAMCFG__CHANSIZE_MASK                                          0x00000100
#define MC_ARB_RAMCFG__CHANSIZE__SHIFT                                        8
#define MC_ARB_RAMCFG__CHANSIZE_OVERRIDE_MASK                                 0x00000800
#define MC_ARB_RAMCFG__CHANSIZE_OVERRIDE__SHIFT                               11
#define MC_ARB_RAMCFG__NOOFCOLS_MASK                                          0x000000C0
#define MC_ARB_RAMCFG__NOOFCOLS__SHIFT                                        6
#define MC_ARB_RAMCFG__NOOFBANK_MASK                                          0x00000003
#define MC_ARB_RAMCFG__NOOFBANK__SHIFT                                        0
#define MC_ARB_RAMCFG__NOOFROWS_MASK                                          0x00000038
#define MC_ARB_RAMCFG__NOOFROWS__SHIFT                                        3
#define MC_ARB_RAMCFG__NOOFGROUPS_MASK                                        0x00001000
#define MC_ARB_RAMCFG__NOOFGROUPS__SHIFT                                      12
#define MC_ARB_BURST_TIME__STATE3_MASK                                        (0x1f << 15)
#define MC_ARB_BURST_TIME__STATE3__SHIFT                                      15
#define MC_ARB_BURST_TIME__STATE2_MASK                                        (0x1f << 10)
#define MC_ARB_BURST_TIME__STATE2__SHIFT                                      10
#define MC_ARB_BURST_TIME__STATE1_MASK                                        (0x1f << 5)
#define MC_ARB_BURST_TIME__STATE1__SHIFT                                      5
#define MC_ARB_BURST_TIME__STATE0_MASK                                        (0x1f << 0)
#define MC_ARB_BURST_TIME__STATE0__SHIFT                                      0
#define MC_SEQ_TRAIN_WAKEUP_CNTL__TRAIN_DONE_D1_MASK                          0x80000000
#define MC_SEQ_TRAIN_WAKEUP_CNTL__TRAIN_DONE_D1__SHIFT                        31
#define MC_SEQ_TRAIN_WAKEUP_CNTL__TRAIN_DONE_D0_MASK                          0x40000000
#define MC_SEQ_TRAIN_WAKEUP_CNTL__TRAIN_DONE_D0__SHIFT                        30
#define MC_SEQ_SUP_CNTL__RUN_MASK                                             (1 << 0)
#define MC_SEQ_SUP_CNTL__RUN__SHIFT                                           0
#define MC_IO_PAD_CNTL_D0__MEM_FALL_OUT_CMD_MASK                              0x00000100
#define MC_IO_PAD_CNTL_D0__MEM_FALL_OUT_CMD__SHIFT                            8
#define MC_SEQ_MISC0__MC_SEQ_MISC0_VEN_ID_MASK                                0x00000f00
#define MC_SEQ_MISC0__MC_SEQ_MISC0_VEN_ID__SHIFT                              8
#define MC_SEQ_MISC0__MC_SEQ_MISC0_GDDR5_MASK                                 0xf0000000
#define MC_SEQ_MISC0__MC_SEQ_MISC0_GDDR5__SHIFT                               28
#define MC_SEQ_MISC0__MC_SEQ_MISC0_REV_ID_MASK                                0x0000f000
#define MC_SEQ_MISC0__MC_SEQ_MISC0_REV_ID__SHIFT                              12

#endif /*__GMC_6_0_SH_MASK_H__*/
