#ifndef __GMC_6_0_D_H__
#define __GMC_6_0_D_H__

#define mmVM_L2_CNTL                                                            0x500
#define mmVM_L2_CNTL2                                                           0x501
#define mmVM_L2_CNTL3                                                           0x502
#define mmVM_L2_STATUS                                                          0x503
#define mmVM_CONTEXT0_CNTL                                                      0x504
#define mmVM_CONTEXT1_CNTL                                                      0x505
#define mmVM_CONTEXT0_CNTL2                                                     0x50c
#define mmVM_CONTEXT1_CNTL2                                                     0x50d
#define mmVM_CONTEXT8_PAGE_TABLE_BASE_ADDR                                      0x50e
#define mmVM_CONTEXT9_PAGE_TABLE_BASE_ADDR                                      0x50f
#define mmVM_CONTEXT10_PAGE_TABLE_BASE_ADDR                                     0x510
#define mmVM_CONTEXT11_PAGE_TABLE_BASE_ADDR                                     0x511
#define mmVM_CONTEXT12_PAGE_TABLE_BASE_ADDR                                     0x512
#define mmVM_CONTEXT13_PAGE_TABLE_BASE_ADDR                                     0x513
#define mmVM_CONTEXT14_PAGE_TABLE_BASE_ADDR                                     0x514
#define mmVM_CONTEXT15_PAGE_TABLE_BASE_ADDR                                     0x515
#define mmVM_CONTEXT1_PROTECTION_FAULT_ADDR                                     0x53f
#define mmVM_CONTEXT1_PROTECTION_FAULT_STATUS                                   0x537
#define mmVM_INVALIDATE_REQUEST                                                 0x51e
#define mmVM_INVALIDATE_RESPONSE                                                0x51f
#define mmVM_CONTEXT0_PROTECTION_FAULT_DEFAULT_ADDR                             0x546
#define mmVM_CONTEXT1_PROTECTION_FAULT_DEFAULT_ADDR                             0x547
#define mmVM_CONTEXT0_PAGE_TABLE_BASE_ADDR                                      0x54f
#define mmVM_CONTEXT1_PAGE_TABLE_BASE_ADDR                                      0x550
#define mmVM_CONTEXT2_PAGE_TABLE_BASE_ADDR                                      0x551
#define mmVM_CONTEXT3_PAGE_TABLE_BASE_ADDR                                      0x552
#define mmVM_CONTEXT4_PAGE_TABLE_BASE_ADDR                                      0x553
#define mmVM_CONTEXT5_PAGE_TABLE_BASE_ADDR                                      0x554
#define mmVM_CONTEXT6_PAGE_TABLE_BASE_ADDR                                      0x555
#define mmVM_CONTEXT7_PAGE_TABLE_BASE_ADDR                                      0x556
#define mmVM_CONTEXT0_PAGE_TABLE_START_ADDR                                     0x557
#define mmVM_CONTEXT1_PAGE_TABLE_START_ADDR                                     0x558
#define mmVM_CONTEXT0_PAGE_TABLE_END_ADDR                                       0x55f
#define mmVM_CONTEXT1_PAGE_TABLE_END_ADDR                                       0x560
#define mmVM_L2_CG                                                              0x570
#define mmMC_SHARED_CHMAP                                                       0x801
#define mmMC_SHARED_CHREMAP                                                     0x802
#define mmMC_VM_FB_LOCATION                                                     0x809
#define mmMC_VM_AGP_TOP                                                         0x80a
#define mmMC_VM_AGP_BOT                                                         0x80b
#define mmMC_VM_AGP_BASE                                                        0x80c
#define mmMC_VM_SYSTEM_APERTURE_LOW_ADDR                                        0x80d
#define mmMC_VM_SYSTEM_APERTURE_HIGH_ADDR                                       0x80e
#define mmMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR                                    0x80f
#define mmMC_VM_MX_L1_TLB_CNTL                                                  0x819
#define mmMC_SHARED_BLACKOUT_CNTL                                               0x82b
#define mmMC_HUB_MISC_HUB_CG                                                    0x82e
#define mmMC_HUB_MISC_VM_CG                                                     0x82f
#define mmMC_HUB_MISC_SIP_CG                                                    0x830
#define mmMC_XPB_CLK_GAT                                                        0x91e
#define mmMC_CITF_MISC_RD_CG                                                    0x992
#define mmMC_CITF_MISC_WR_CG                                                    0x993
#define mmMC_CITF_MISC_VM_CG                                                    0x994
#define mmMC_ARB_RAMCFG                                                         0x9d8
#define mmMC_ARB_DRAM_TIMING                                                    0x9dd
#define mmMC_ARB_DRAM_TIMING2                                                   0x9de
#define mmMC_ARB_BURST_TIME                                                     0xa02
#define mmMC_SEQ_TRAIN_WAKEUP_CNTL                                              0xa3a
#define mmMC_SEQ_SUP_CNTL                                                       0xa32
#define mmMC_SEQ_SUP_PGM                                                        0xa33
#define mmMC_PMG_AUTO_CMD                                                       0xa34
#define mmMC_IO_PAD_CNTL_D0                                                     0xa74
#define mmMC_SEQ_RAS_TIMING                                                     0xa28
#define mmMC_SEQ_CAS_TIMING                                                     0xa29
#define mmMC_SEQ_MISC_TIMING                                                    0xa2a
#define mmMC_SEQ_MISC_TIMING2                                                   0xa2b
#define mmMC_SEQ_PMG_TIMING                                                     0xa2c
#define mmMC_SEQ_RD_CTL_D0                                                      0xa2d
#define mmMC_SEQ_RD_CTL_D1                                                      0xa2e
#define mmMC_SEQ_WR_CTL_D0                                                      0xa2f
#define mmMC_SEQ_WR_CTL_D1                                                      0xa30
#define mmMC_SEQ_MISC0                                                          0xa80
#define mmMC_SEQ_MISC1                                                          0xa81
#define mmMC_SEQ_RESERVE_M                                                      0xa82
#define mmMC_PMG_CMD_EMRS                                                       0xa83
#define mmMC_SEQ_IO_DEBUG_INDEX                                                 0xa91
#define mmMC_SEQ_IO_DEBUG_DATA                                                  0xa92
#define mmMC_SEQ_MISC5                                                          0xa95
#define mmMC_SEQ_MISC6                                                          0xa96
#define mmMC_SEQ_MISC7                                                          0xa99
#define mmMC_SEQ_RAS_TIMING_LP                                                  0xa9b
#define mmMC_SEQ_CAS_TIMING_LP                                                  0xa9c
#define mmMC_SEQ_MISC_TIMING_LP                                                 0xa9d
#define mmMC_SEQ_MISC_TIMING2_LP                                                0xa9e
#define mmMC_SEQ_WR_CTL_D0_LP                                                   0xa9f
#define mmMC_SEQ_WR_CTL_D1_LP                                                   0xaa0
#define mmMC_SEQ_PMG_CMD_EMRS_LP                                                0xaa1
#define mmMC_SEQ_PMG_CMD_MRS_LP                                                 0xaa2
#define mmMC_PMG_CMD_MRS                                                        0xaab
#define mmMC_SEQ_RD_CTL_D0_LP                                                   0xac7
#define mmMC_SEQ_RD_CTL_D1_LP                                                   0xac8
#define mmMC_PMG_CMD_MRS1                                                       0xad1
#define mmMC_SEQ_PMG_CMD_MRS1_LP                                                0xad2
#define mmMC_SEQ_PMG_TIMING_LP                                                  0xad3
#define mmMC_SEQ_WR_CTL_2                                                       0xad5
#define mmMC_SEQ_WR_CTL_2_LP                                                    0xad6
#define mmMC_PMG_CMD_MRS2                                                       0xad7
#define mmMC_SEQ_PMG_CMD_MRS2_LP                                                0xad8
#define mmATC_MISC_CG                                                           0xcd4

#endif /*__GMC_6_0_D_H__*/
