#ifndef __SMU_6_0_D_H__
#define __SMU_6_0_D_H__

#define mmSMC_IND_INDEX_0                                                       0x80
#define mmSMC_IND_DATA_0                                                        0x81
#define mmSMC_IND_ACCESS_CNTL                                                   0x8a
#define mmSMC_MESSAGE_0                                                         0x8b
#define mmSMC_RESP_0                                                            0x8c
#define mmSMC_CG_IND_START                                                      0x3000c000
#define mmSMC_CG_IND_END                                                        0x30010000
#define mmCG_CGTT_LOCAL_0                                                       0x100
#define mmSMC_SYSCON_RESET_CNTL                                                 0x20000000
#define mmSMC_SYSCON_CLOCK_CNTL_0                                               0x20000001
#define mmCG_SPLL_FUNC_CNTL                                                     0x180
#define mmCG_SPLL_FUNC_CNTL_2                                                   0x181
#define mmCG_SPLL_FUNC_CNTL_3                                                   0x182
#define mmCG_SPLL_FUNC_CNTL_4                                                   0x183
#define mmSPLL_STATUS                                                           0x185
#define mmSPLL_CNTL_MODE                                                        0x186
#define mmCG_SPLL_SPREAD_SPECTRUM                                               0x188
#define mmCG_SPLL_SPREAD_SPECTRUM_2                                             0x189
#define mmCG_SPLL_AUTOSCALE_CNTL                                                0x18b
#define mmCG_UPLL_FUNC_CNTL                                                     0x18d
#define mmCG_UPLL_FUNC_CNTL_2                                                   0x18e
#define mmCG_UPLL_FUNC_CNTL_3                                                   0x18f
#define mmCG_UPLL_FUNC_CNTL_4                                                   0x191
#define mmCG_UPLL_FUNC_CNTL_5                                                   0x192
#define mmCG_UPLL_SPREAD_SPECTRUM                                               0x194
#define mmMPLL_BYPASSCLK_SEL                                                    0x197
#define mmCG_CLKPIN_CNTL                                                        0x198
#define mmCG_CLKPIN_CNTL_2                                                      0x199
#define mmTHM_CLK_CNTL                                                          0x19b
#define mmMISC_CLK_CNTL                                                         0x19c
#define mmCG_THERMAL_CTRL                                                       0x1c0
#define mmCG_THERMAL_STATUS                                                     0x1c1
#define mmCG_THERMAL_INT                                                        0x1c2
#define mmCG_MULT_THERMAL_CTRL                                                  0x1c4
#define mmCG_MULT_THERMAL_STATUS                                                0x1c5
#define mmCG_FDO_CTRL0                                                          0x1d5
#define mmCG_FDO_CTRL1                                                          0x1d6
#define mmCG_FDO_CTRL2                                                          0x1d7
#define mmCG_TACH_CTRL                                                          0x1dc
#define mmCG_TACH_STATUS                                                        0x1dd
#define mmGENERAL_PWRMGT                                                        0x1e0
#define mmCG_TPC                                                                0x1e1
#define mmSCLK_PWRMGT_CNTL                                                      0x1e2
#define mmTARGET_AND_CURRENT_PROFILE_INDEX                                      0x1e6
#define mmCG_FTV                                                                0x1ef
#define mmCG_FFCT_0                                                             0x1f0
#define mmCG_BSP                                                                0x1ff
#define mmCG_AT                                                                 0x200
#define mmCG_GIT                                                                0x201
#define mmCG_SSP                                                                0x203
#define mmCG_DISPLAY_GAP_CNTL                                                   0x20a
#define mmCG_ULV_CONTROL                                                        0x21e
#define mmCG_ULV_PARAMETER                                                      0x21f
#define mmSMC_SCRATCH0                                                          0x221
#define mmCG_CAC_CTRL                                                           0x22e
#define mmDMIF_ADDR_CONFIG                                                      0x2f5
#define mmDMIF_ADDR_CALC                                                        0x300
#define mmMPLL_CNTL_MODE                                                        0xaec
#define mmMPLL_FUNC_CNTL                                                        0xaed
#define mmMPLL_FUNC_CNTL_1                                                      0xaee
#define mmMPLL_FUNC_CNTL_2                                                      0xaef
#define mmMPLL_AD_FUNC_CNTL                                                     0xaf0
#define mmMPLL_DQ_FUNC_CNTL                                                     0xaf1
#define mmMPLL_SS1                                                              0xaf3
#define mmMPLL_SS2                                                              0xaf4
#define ixCG_VCEPLL_FUNC_CNTL                                                   0xc0030600
#define ixCG_VCEPLL_FUNC_CNTL_2                                                 0xc0030601
#define ixCG_VCEPLL_FUNC_CNTL_3                                                 0xc0030602
#define ixCG_VCEPLL_FUNC_CNTL_4                                                 0xc0030603
#define ixCG_VCEPLL_FUNC_CNTL_5                                                 0xc0030604
#define ixCG_VCEPLL_SPREAD_SPECTRUM                                             0xc0030606

#endif /*__SMU_6_0_D_H__*/
