#ifndef __BIF_4_0_ENUM_H__
#define __BIF_4_0_ENUM_H__

typedef enum PCIE_LC_LINK_WIDTH_CNTL {
	PCIE_LC_LINK_WIDTH_CNTL__LC_LINK_WIDTH_X0          = 0,
	PCIE_LC_LINK_WIDTH_CNTL__LC_LINK_WIDTH_X1          = 1,
	PCIE_LC_LINK_WIDTH_CNTL__LC_LINK_WIDTH_X2          = 2,
	PCIE_LC_LINK_WIDTH_CNTL__LC_LINK_WIDTH_X4          = 3,
	PCIE_LC_LINK_WIDTH_CNTL__LC_LINK_WIDTH_X8          = 4,
	PCIE_LC_LINK_WIDTH_CNTL__LC_LINK_WIDTH_X16         = 6,
} PCIE_LC_LINK_WIDTH_CNTL;

#endif /*__BIF_4_0_ENUM_H__*/
