#ifndef __DCE_7_0_D_H__
#define __DCE_7_0_D_H__

#define mmDCCG_DISP_SLOW_SELECT_REG                                             0x13f
#define mmAZ_F0_CODEC_ENDPOINT_INDEX                                            0x1780
#define mmAZ_F0_CODEC_ENDPOINT_DATA                                             0x1781
#define mmAZ_F0_CODEC_PIN_CONTROL_AUDIO_DESCRIPTOR0                             0xa
#define mmAZ_F0_CODEC_PIN_CONTROL_AUDIO_DESCRIPTOR4                             0xb
#define mmAZ_F0_CODEC_PIN_CONTROL_AUDIO_DESCRIPTOR8                             0xc
#define mmAZ_F0_CODEC_PIN_CONTROL_AUDIO_DESCRIPTOR12                            0xd
#define mmAZ_F0_CODEC_PIN_CONTROL_RESPONSE_HBR                                  0xe
#define mmAZ_F0_CODEC_PIN_CONTROL_SINK_INFO2                                    0xf
#define mmAZ_F0_CODEC_PIN_CONTROL_SINK_INFO6                                    0x10
#define mmAZ_F0_CODEC_PIN_CONTROL_HOT_PLUG_CONTROL                              0x15
#define mmDC_LB_MEMORY_SPLIT                                                    0x1ac3
#define mmVLINE_STATUS                                                          0x1aee
#define mmVBLANK_STATUS                                                         0x1aef
#define mmDISP_INTERRUPT_STATUS                                                 0x183d
#define mmDISP_INTERRUPT_STATUS_CONTINUE                                        0x183e
#define mmDISP_INTERRUPT_STATUS_CONTINUE2                                       0x183f
#define mmDISP_INTERRUPT_STATUS_CONTINUE3                                       0x1840
#define mmDISP_INTERRUPT_STATUS_CONTINUE4                                       0x1853
#define mmDISP_INTERRUPT_STATUS_CONTINUE5                                       0x1854
#define mmDC_HPD1_INT_STATUS                                                    0x1807
#define mmDC_HPD2_INT_STATUS                                                    0x180a
#define mmDC_HPD3_INT_STATUS                                                    0x180d
#define mmDC_HPD4_INT_STATUS                                                    0x1810
#define mmDC_HPD5_INT_STATUS                                                    0x1813
#define mmDC_HPD6_INT_STATUS                                                    0x1816
#define mmDC_HPD1_INT_CONTROL                                                   0x1808
#define mmDC_HPD2_INT_CONTROL                                                   0x180b
#define mmDC_HPD3_INT_CONTROL                                                   0x180e
#define mmDC_HPD4_INT_CONTROL                                                   0x1811
#define mmDC_HPD5_INT_CONTROL                                                   0x1814
#define mmDC_HPD6_INT_CONTROL                                                   0x1817
#define mmDC_HPD1_CONTROL                                                       0x1809
#define mmDC_HPD2_CONTROL                                                       0x180c
#define mmDC_HPD3_CONTROL                                                       0x180f
#define mmDC_HPD4_CONTROL                                                       0x1812
#define mmDC_HPD5_CONTROL                                                       0x1815
#define mmDC_HPD6_CONTROL                                                       0x1818
#define mmDPG_PIPE_STUTTER_CONTROL                                              0x1b35
#define mmCRTC_STATUS_FRAME_COUNT                                               0x1ba6
#define mmDCCG_AUDIO_DTO_SOURCE                                                 0x16b
#define mmDCCG_AUDIO_DTO0_PHASE                                                 0x16c
#define mmDCCG_AUDIO_DTO0_MODULE                                                0x16d
#define mmDCCG_AUDIO_DTO1_PHASE                                                 0x170
#define mmDCCG_AUDIO_DTO1_MODULE                                                0x171
#define mmDENTIST_DISPCLK_CNTL                                                  0x124
#define mmAFMT_AUDIO_SRC_CONTROL                                                0x1c4f
#define mmD1CRTC_CONTROL                                                        0x1820
#define mmD1CRTC_STATUS                                                         0x1827
#define mmD1CRTC_UPDATE_LOCK                                                    0x183a
#define mmD2CRTC_CONTROL                                                        0x1a20
#define mmD2CRTC_STATUS                                                         0x1a27
#define mmD2CRTC_UPDATE_LOCK                                                    0x1a3a
#define mmD1VGA_CONTROL                                                         0xcc
#define mmD2VGA_CONTROL                                                         0xce
#define mmVGA_HDP_CONTROL                                                       0xca
#define mmVGA_MEMORY_BASE_ADDRESS                                               0xc4
#define mmVGA_RENDER_CONTROL                                                    0xc0

#endif /*__DCE_7_0_D_H__*/
