#ifndef __DCE_6_0_SH_MASK_H__
#define __DCE_6_0_SH_MASK_H__

#define DCCG_DISP_SLOW_SELECT_REG__DCCG_DISP1_SLOW_SELECT_MASK                (7 << 0)
#define DCCG_DISP_SLOW_SELECT_REG__DCCG_DISP1_SLOW_SELECT__SHIFT              0
#define DCCG_DISP_SLOW_SELECT_REG__DCCG_DISP2_SLOW_SELECT_MASK                (7 << 4)
#define DCCG_DISP_SLOW_SELECT_REG__DCCG_DISP2_SLOW_SELECT__SHIFT              4
#define PIPE0_DMIF_BUFFER_CONTROL__DMIF_BUFFERS_ALLOCATED_MASK                0x7
#define PIPE0_DMIF_BUFFER_CONTROL__DMIF_BUFFERS_ALLOCATED__SHIFT              0
#define PIPE0_DMIF_BUFFER_CONTROL__DMIF_BUFFERS_ALLOCATED_COMPLETED_MASK      0x00000010
#define PIPE0_DMIF_BUFFER_CONTROL__DMIF_BUFFERS_ALLOCATED_COMPLETED__SHIFT    4
#define AZ_F0_CODEC_ENDPOINT_INDEX__AZ_ENDPOINT_REG_WRITE_EN_MASK             0x00000100
#define AZ_F0_CODEC_ENDPOINT_INDEX__AZ_ENDPOINT_REG_WRITE_EN__SHIFT           8
#define AZ_F0_CODEC_ENDPOINT_DATA__SPEAKER_ALLOCATION_MASK                    (0x7f << 0)
#define AZ_F0_CODEC_ENDPOINT_DATA__SPEAKER_ALLOCATION__SHIFT                  0
#define AZ_F0_CODEC_ENDPOINT_DATA__DP_CONNECTION_MASK                         0x00020000
#define AZ_F0_CODEC_ENDPOINT_DATA__DP_CONNECTION__SHIFT                       17
#define AZ_F0_CODEC_ENDPOINT_DATA__HDMI_CONNECTION_MASK                       0x00010000
#define AZ_F0_CODEC_ENDPOINT_DATA__HDMI_CONNECTION__SHIFT                     16
#define AZ_F0_CODEC_PIN_CONTROL_RESPONSE_HBR__HBR_CAPABLE_MASK                0x00000001
#define AZ_F0_CODEC_PIN_CONTROL_RESPONSE_HBR__HBR_CAPABLE__SHIFT              0
#define AZ_F0_CODEC_PIN_CONTROL_HOT_PLUG_CONTROL__PORT_CONNECTIVITY_MASK      (3 << 30)
#define AZ_F0_CODEC_PIN_CONTROL_HOT_PLUG_CONTROL__PORT_CONNECTIVITY__SHIFT    30
#define AZ_F0_CODEC_PIN_CONTROL_HOT_PLUG_CONTROL__AUDIO_ENABLED_MASK          0x80000000
#define AZ_F0_CODEC_PIN_CONTROL_HOT_PLUG_CONTROL__AUDIO_ENABLED__SHIFT        31
#define DC_LB_MEMORY_SPLIT__LB_MEMORY_CONFIG_MASK                             (3 << 20)
#define DC_LB_MEMORY_SPLIT__LB_MEMORY_CONFIG__SHIFT                           20
#define PRIORITY_A_CNT__PRIORITY_OFF_MASK                                     0x00010000
#define PRIORITY_A_CNT__PRIORITY_OFF__SHIFT                                   16
#define PRIORITY_A_CNT__PRIORITY_MARK_MASK                                    0x7fff
#define PRIORITY_A_CNT__PRIORITY_MARK__SHIFT                                  0
#define PRIORITY_A_CNT__PRIORITY_ALWAYS_ON_MASK                               0x00100000
#define PRIORITY_A_CNT__PRIORITY_ALWAYS_ON__SHIFT                             20
#define DPG_PIPE_ARBITRATION_CONTROL3__LATENCY_WATERMARK_MASK                 (3 << 16)
#define DPG_PIPE_ARBITRATION_CONTROL3__LATENCY_WATERMARK__SHIFT               16
#define DPG_PIPE_LATENCY_CONTROL__LATENCY_LOW_WATERMARK_MASK                  0xffff
#define DPG_PIPE_LATENCY_CONTROL__LATENCY_LOW_WATERMARK__SHIFT                0
#define DPG_PIPE_LATENCY_CONTROL__LATENCY_HIGH_WATERMARK_MASK                 (0xffff << 16)
#define DPG_PIPE_LATENCY_CONTROL__LATENCY_HIGH_WATERMARK__SHIFT               16
#define LB_VLINE_STATUS__VLINE_OCCURRED_MASK                                  0x00000001
#define LB_VLINE_STATUS__VLINE_OCCURRED__SHIFT                                0
#define LB_VLINE_STATUS__VLINE_INTERRUPT_MASK                                 0x00010000
#define LB_VLINE_STATUS__VLINE_INTERRUPT__SHIFT                               16
#define LB_VLINE_STATUS__VLINE_STAT_MASK                                      0x00001000
#define LB_VLINE_STATUS__VLINE_STAT__SHIFT                                    12
#define LB_VLINE_STATUS__VLINE_INTERRUPT_TYPE_MASK                            0x00020000
#define LB_VLINE_STATUS__VLINE_INTERRUPT_TYPE__SHIFT                          17
#define LB_VLINE_STATUS__VLINE_ACK_MASK                                       0x00000010
#define LB_VLINE_STATUS__VLINE_ACK__SHIFT                                     4
#define LB_VBLANK_STATUS__VBLANK_INTERRUPT_MASK                               0x00010000
#define LB_VBLANK_STATUS__VBLANK_INTERRUPT__SHIFT                             16
#define LB_VBLANK_STATUS__VBLANK_OCCURRED_MASK                                0x00000001
#define LB_VBLANK_STATUS__VBLANK_OCCURRED__SHIFT                              0
#define LB_VBLANK_STATUS__VBLANK_INTERRUPT_TYPE_MASK                          0x00020000
#define LB_VBLANK_STATUS__VBLANK_INTERRUPT_TYPE__SHIFT                        17
#define LB_VBLANK_STATUS__VBLANK_ACK_MASK                                     0x00000010
#define LB_VBLANK_STATUS__VBLANK_ACK__SHIFT                                   4
#define LB_VBLANK_STATUS__VBLANK_STAT_MASK                                    0x00001000
#define LB_VBLANK_STATUS__VBLANK_STAT__SHIFT                                  12
#define LB_INT_MASK__VBLANK_INT_MASK                                          (1 << 0)
#define LB_INT_MASK__VBLANK_INT__SHIFT                                        0
#define LB_INT_MASK__VLINE_INT_MASK                                           (1 << 4)
#define LB_INT_MASK__VLINE_INT__SHIFT                                         4
#define DISP_INTERRUPT_STATUS__DC_I2C_HW_DONE_INTERRUPT_MASK                  0x02000000
#define DISP_INTERRUPT_STATUS__DC_I2C_HW_DONE_INTERRUPT__SHIFT                25
#define DISP_INTERRUPT_STATUS__LB_D1_VBLANK_INTERRUPT_MASK                    0x00000008
#define DISP_INTERRUPT_STATUS__LB_D1_VBLANK_INTERRUPT__SHIFT                  3
#define DISP_INTERRUPT_STATUS__DC_HPD1_RX_INTERRUPT_MASK                      0x00040000
#define DISP_INTERRUPT_STATUS__DC_HPD1_RX_INTERRUPT__SHIFT                    18
#define DISP_INTERRUPT_STATUS__DACA_AUTODETECT_INTERRUPT_MASK                 0x00400000
#define DISP_INTERRUPT_STATUS__DACA_AUTODETECT_INTERRUPT__SHIFT               22
#define DISP_INTERRUPT_STATUS__DC_HPD1_INTERRUPT_MASK                         0x00020000
#define DISP_INTERRUPT_STATUS__DC_HPD1_INTERRUPT__SHIFT                       17
#define DISP_INTERRUPT_STATUS__DACB_AUTODETECT_INTERRUPT_MASK                 0x00800000
#define DISP_INTERRUPT_STATUS__DACB_AUTODETECT_INTERRUPT__SHIFT               23
#define DISP_INTERRUPT_STATUS__DC_I2C_SW_DONE_INTERRUPT_MASK                  0x01000000
#define DISP_INTERRUPT_STATUS__DC_I2C_SW_DONE_INTERRUPT__SHIFT                24
#define DISP_INTERRUPT_STATUS__LB_D1_VLINE_INTERRUPT_MASK                     0x00000004
#define DISP_INTERRUPT_STATUS__LB_D1_VLINE_INTERRUPT__SHIFT                   2
#define DISP_INTERRUPT_STATUS_CONTINUE__LB_D2_VBLANK_INTERRUPT_MASK           0x00000008
#define DISP_INTERRUPT_STATUS_CONTINUE__LB_D2_VBLANK_INTERRUPT__SHIFT         3
#define DISP_INTERRUPT_STATUS_CONTINUE__DC_HPD2_RX_INTERRUPT_MASK             0x00040000
#define DISP_INTERRUPT_STATUS_CONTINUE__DC_HPD2_RX_INTERRUPT__SHIFT           18
#define DISP_INTERRUPT_STATUS_CONTINUE__DC_HPD2_INTERRUPT_MASK                0x00020000
#define DISP_INTERRUPT_STATUS_CONTINUE__DC_HPD2_INTERRUPT__SHIFT              17
#define DISP_INTERRUPT_STATUS_CONTINUE__DISP_TIMER_INTERRUPT_MASK             0x01000000
#define DISP_INTERRUPT_STATUS_CONTINUE__DISP_TIMER_INTERRUPT__SHIFT           24
#define DISP_INTERRUPT_STATUS_CONTINUE__LB_D2_VLINE_INTERRUPT_MASK            0x00000004
#define DISP_INTERRUPT_STATUS_CONTINUE__LB_D2_VLINE_INTERRUPT__SHIFT          2
#define DISP_INTERRUPT_STATUS_CONTINUE2__DC_HPD3_INTERRUPT_MASK               0x00020000
#define DISP_INTERRUPT_STATUS_CONTINUE2__DC_HPD3_INTERRUPT__SHIFT             17
#define DISP_INTERRUPT_STATUS_CONTINUE2__DC_HPD3_RX_INTERRUPT_MASK            0x00040000
#define DISP_INTERRUPT_STATUS_CONTINUE2__DC_HPD3_RX_INTERRUPT__SHIFT          18
#define DISP_INTERRUPT_STATUS_CONTINUE2__LB_D3_VBLANK_INTERRUPT_MASK          0x00000008
#define DISP_INTERRUPT_STATUS_CONTINUE2__LB_D3_VBLANK_INTERRUPT__SHIFT        3
#define DISP_INTERRUPT_STATUS_CONTINUE2__LB_D3_VLINE_INTERRUPT_MASK           0x00000004
#define DISP_INTERRUPT_STATUS_CONTINUE2__LB_D3_VLINE_INTERRUPT__SHIFT         2
#define DISP_INTERRUPT_STATUS_CONTINUE3__DC_HPD4_RX_INTERRUPT_MASK            0x00040000
#define DISP_INTERRUPT_STATUS_CONTINUE3__DC_HPD4_RX_INTERRUPT__SHIFT          18
#define DISP_INTERRUPT_STATUS_CONTINUE3__DC_HPD4_INTERRUPT_MASK               0x00020000
#define DISP_INTERRUPT_STATUS_CONTINUE3__DC_HPD4_INTERRUPT__SHIFT             17
#define DISP_INTERRUPT_STATUS_CONTINUE3__LB_D4_VLINE_INTERRUPT_MASK           0x00000004
#define DISP_INTERRUPT_STATUS_CONTINUE3__LB_D4_VLINE_INTERRUPT__SHIFT         2
#define DISP_INTERRUPT_STATUS_CONTINUE3__LB_D4_VBLANK_INTERRUPT_MASK          0x00000008
#define DISP_INTERRUPT_STATUS_CONTINUE3__LB_D4_VBLANK_INTERRUPT__SHIFT        3
#define DISP_INTERRUPT_STATUS_CONTINUE4__LB_D5_VBLANK_INTERRUPT_MASK          0x00000008
#define DISP_INTERRUPT_STATUS_CONTINUE4__LB_D5_VBLANK_INTERRUPT__SHIFT        3
#define DISP_INTERRUPT_STATUS_CONTINUE4__DC_HPD5_RX_INTERRUPT_MASK            0x00040000
#define DISP_INTERRUPT_STATUS_CONTINUE4__DC_HPD5_RX_INTERRUPT__SHIFT          18
#define DISP_INTERRUPT_STATUS_CONTINUE4__LB_D5_VLINE_INTERRUPT_MASK           0x00000004
#define DISP_INTERRUPT_STATUS_CONTINUE4__LB_D5_VLINE_INTERRUPT__SHIFT         2
#define DISP_INTERRUPT_STATUS_CONTINUE4__DC_HPD5_INTERRUPT_MASK               0x00020000
#define DISP_INTERRUPT_STATUS_CONTINUE4__DC_HPD5_INTERRUPT__SHIFT             17
#define DISP_INTERRUPT_STATUS_CONTINUE5__DC_HPD6_INTERRUPT_MASK               0x00020000
#define DISP_INTERRUPT_STATUS_CONTINUE5__DC_HPD6_INTERRUPT__SHIFT             17
#define DISP_INTERRUPT_STATUS_CONTINUE5__LB_D6_VLINE_INTERRUPT_MASK           0x00000004
#define DISP_INTERRUPT_STATUS_CONTINUE5__LB_D6_VLINE_INTERRUPT__SHIFT         2
#define DISP_INTERRUPT_STATUS_CONTINUE5__LB_D6_VBLANK_INTERRUPT_MASK          0x00000008
#define DISP_INTERRUPT_STATUS_CONTINUE5__LB_D6_VBLANK_INTERRUPT__SHIFT        3
#define DISP_INTERRUPT_STATUS_CONTINUE5__DC_HPD6_RX_INTERRUPT_MASK            0x00040000
#define DISP_INTERRUPT_STATUS_CONTINUE5__DC_HPD6_RX_INTERRUPT__SHIFT          18
#define GRPH_INT_STATUS__GRPH_PFLIP_INT_OCCURRED_MASK                         0x00000001
#define GRPH_INT_STATUS__GRPH_PFLIP_INT_OCCURRED__SHIFT                       0
#define GRPH_INT_STATUS__GRPH_PFLIP_INT_CLEAR_MASK                            0x00000100
#define GRPH_INT_STATUS__GRPH_PFLIP_INT_CLEAR__SHIFT                          8
#define GRPH_INT_CONTROL__GRPH_PFLIP_INT_TYPE_MASK                            0x00000100
#define GRPH_INT_CONTROL__GRPH_PFLIP_INT_TYPE__SHIFT                          8
#define GRPH_INT_CONTROL__GRPH_PFLIP_INT_MASK                                 (1 << 0)
#define GRPH_INT_CONTROL__GRPH_PFLIP_INT__SHIFT                               0
#define DC_HPD1_INT_STATUS__DC_HPD1_SENSE_MASK                                0x00000002
#define DC_HPD1_INT_STATUS__DC_HPD1_SENSE__SHIFT                              1
#define DC_HPD1_INT_STATUS__DC_HPD1_INT_STATUS_MASK                           0x00000001
#define DC_HPD1_INT_STATUS__DC_HPD1_INT_STATUS__SHIFT                         0
#define DC_HPD1_INT_STATUS__DC_HPD1_RX_INT_STATUS_MASK                        0x00000100
#define DC_HPD1_INT_STATUS__DC_HPD1_RX_INT_STATUS__SHIFT                      8
#define DC_HPD2_INT_STATUS__DC_HPD2_INT_STATUS_MASK                           0x00000001
#define DC_HPD2_INT_STATUS__DC_HPD2_INT_STATUS__SHIFT                         0
#define DC_HPD2_INT_STATUS__DC_HPD2_SENSE_MASK                                0x00000002
#define DC_HPD2_INT_STATUS__DC_HPD2_SENSE__SHIFT                              1
#define DC_HPD2_INT_STATUS__DC_HPD2_RX_INT_STATUS_MASK                        0x00000100
#define DC_HPD2_INT_STATUS__DC_HPD2_RX_INT_STATUS__SHIFT                      8
#define DC_HPD3_INT_STATUS__DC_HPD3_RX_INT_STATUS_MASK                        0x00000100
#define DC_HPD3_INT_STATUS__DC_HPD3_RX_INT_STATUS__SHIFT                      8
#define DC_HPD3_INT_STATUS__DC_HPD3_INT_STATUS_MASK                           0x00000001
#define DC_HPD3_INT_STATUS__DC_HPD3_INT_STATUS__SHIFT                         0
#define DC_HPD3_INT_STATUS__DC_HPD3_SENSE_MASK                                0x00000002
#define DC_HPD3_INT_STATUS__DC_HPD3_SENSE__SHIFT                              1
#define DC_HPD4_INT_STATUS__DC_HPD4_SENSE_MASK                                0x00000002
#define DC_HPD4_INT_STATUS__DC_HPD4_SENSE__SHIFT                              1
#define DC_HPD4_INT_STATUS__DC_HPD4_INT_STATUS_MASK                           0x00000001
#define DC_HPD4_INT_STATUS__DC_HPD4_INT_STATUS__SHIFT                         0
#define DC_HPD4_INT_STATUS__DC_HPD4_RX_INT_STATUS_MASK                        0x00000100
#define DC_HPD4_INT_STATUS__DC_HPD4_RX_INT_STATUS__SHIFT                      8
#define DC_HPD5_INT_STATUS__DC_HPD5_INT_STATUS_MASK                           0x00000001
#define DC_HPD5_INT_STATUS__DC_HPD5_INT_STATUS__SHIFT                         0
#define DC_HPD5_INT_STATUS__DC_HPD5_RX_INT_STATUS_MASK                        0x00000100
#define DC_HPD5_INT_STATUS__DC_HPD5_RX_INT_STATUS__SHIFT                      8
#define DC_HPD5_INT_STATUS__DC_HPD5_SENSE_MASK                                0x00000002
#define DC_HPD5_INT_STATUS__DC_HPD5_SENSE__SHIFT                              1
#define DC_HPD6_INT_STATUS__DC_HPD6_RX_INT_STATUS_MASK                        0x00000100
#define DC_HPD6_INT_STATUS__DC_HPD6_RX_INT_STATUS__SHIFT                      8
#define DC_HPD6_INT_STATUS__DC_HPD6_INT_STATUS_MASK                           0x00000001
#define DC_HPD6_INT_STATUS__DC_HPD6_INT_STATUS__SHIFT                         0
#define DC_HPD6_INT_STATUS__DC_HPD6_SENSE_MASK                                0x00000002
#define DC_HPD6_INT_STATUS__DC_HPD6_SENSE__SHIFT                              1
#define DC_HPD1_INT_CONTROL__DC_HPD1_INT_POLARITY_MASK                        0x00000100
#define DC_HPD1_INT_CONTROL__DC_HPD1_INT_POLARITY__SHIFT                      8
#define DC_HPD1_INT_CONTROL__DC_HPD1_RX_INT_ACK_MASK                          0x00100000
#define DC_HPD1_INT_CONTROL__DC_HPD1_RX_INT_ACK__SHIFT                        20
#define DC_HPD1_INT_CONTROL__DC_HPD1_INT_ACK_MASK                             0x00000001
#define DC_HPD1_INT_CONTROL__DC_HPD1_INT_ACK__SHIFT                           0
#define DC_HPD1_INT_CONTROL__DC_HPD1_RX_INT_EN_MASK                           0x01000000
#define DC_HPD1_INT_CONTROL__DC_HPD1_RX_INT_EN__SHIFT                         24
#define DC_HPD1_INT_CONTROL__DC_HPD1_INT_EN_MASK                              0x00010000
#define DC_HPD1_INT_CONTROL__DC_HPD1_INT_EN__SHIFT                            16
#define DC_HPD2_INT_CONTROL__DC_HPD2_RX_INT_EN_MASK                           0x01000000
#define DC_HPD2_INT_CONTROL__DC_HPD2_RX_INT_EN__SHIFT                         24
#define DC_HPD2_INT_CONTROL__DC_HPD2_RX_INT_ACK_MASK                          0x00100000
#define DC_HPD2_INT_CONTROL__DC_HPD2_RX_INT_ACK__SHIFT                        20
#define DC_HPD2_INT_CONTROL__DC_HPD2_INT_POLARITY_MASK                        0x00000100
#define DC_HPD2_INT_CONTROL__DC_HPD2_INT_POLARITY__SHIFT                      8
#define DC_HPD2_INT_CONTROL__DC_HPD2_INT_EN_MASK                              0x00010000
#define DC_HPD2_INT_CONTROL__DC_HPD2_INT_EN__SHIFT                            16
#define DC_HPD2_INT_CONTROL__DC_HPD2_INT_ACK_MASK                             0x00000001
#define DC_HPD2_INT_CONTROL__DC_HPD2_INT_ACK__SHIFT                           0
#define DC_HPD3_INT_CONTROL__DC_HPD3_INT_ACK_MASK                             0x00000001
#define DC_HPD3_INT_CONTROL__DC_HPD3_INT_ACK__SHIFT                           0
#define DC_HPD3_INT_CONTROL__DC_HPD3_RX_INT_EN_MASK                           0x01000000
#define DC_HPD3_INT_CONTROL__DC_HPD3_RX_INT_EN__SHIFT                         24
#define DC_HPD3_INT_CONTROL__DC_HPD3_RX_INT_ACK_MASK                          0x00100000
#define DC_HPD3_INT_CONTROL__DC_HPD3_RX_INT_ACK__SHIFT                        20
#define DC_HPD3_INT_CONTROL__DC_HPD3_INT_POLARITY_MASK                        0x00000100
#define DC_HPD3_INT_CONTROL__DC_HPD3_INT_POLARITY__SHIFT                      8
#define DC_HPD3_INT_CONTROL__DC_HPD3_INT_EN_MASK                              0x00010000
#define DC_HPD3_INT_CONTROL__DC_HPD3_INT_EN__SHIFT                            16
#define DC_HPD4_INT_CONTROL__DC_HPD4_RX_INT_EN_MASK                           0x01000000
#define DC_HPD4_INT_CONTROL__DC_HPD4_RX_INT_EN__SHIFT                         24
#define DC_HPD4_INT_CONTROL__DC_HPD4_INT_POLARITY_MASK                        0x00000100
#define DC_HPD4_INT_CONTROL__DC_HPD4_INT_POLARITY__SHIFT                      8
#define DC_HPD4_INT_CONTROL__DC_HPD4_INT_EN_MASK                              0x00010000
#define DC_HPD4_INT_CONTROL__DC_HPD4_INT_EN__SHIFT                            16
#define DC_HPD4_INT_CONTROL__DC_HPD4_INT_ACK_MASK                             0x00000001
#define DC_HPD4_INT_CONTROL__DC_HPD4_INT_ACK__SHIFT                           0
#define DC_HPD4_INT_CONTROL__DC_HPD4_RX_INT_ACK_MASK                          0x00100000
#define DC_HPD4_INT_CONTROL__DC_HPD4_RX_INT_ACK__SHIFT                        20
#define DC_HPD5_INT_CONTROL__DC_HPD5_INT_ACK_MASK                             0x00000001
#define DC_HPD5_INT_CONTROL__DC_HPD5_INT_ACK__SHIFT                           0
#define DC_HPD5_INT_CONTROL__DC_HPD5_INT_POLARITY_MASK                        0x00000100
#define DC_HPD5_INT_CONTROL__DC_HPD5_INT_POLARITY__SHIFT                      8
#define DC_HPD5_INT_CONTROL__DC_HPD5_INT_EN_MASK                              0x00010000
#define DC_HPD5_INT_CONTROL__DC_HPD5_INT_EN__SHIFT                            16
#define DC_HPD5_INT_CONTROL__DC_HPD5_RX_INT_EN_MASK                           0x01000000
#define DC_HPD5_INT_CONTROL__DC_HPD5_RX_INT_EN__SHIFT                         24
#define DC_HPD5_INT_CONTROL__DC_HPD5_RX_INT_ACK_MASK                          0x00100000
#define DC_HPD5_INT_CONTROL__DC_HPD5_RX_INT_ACK__SHIFT                        20
#define DC_HPD6_INT_CONTROL__DC_HPD6_INT_POLARITY_MASK                        0x00000100
#define DC_HPD6_INT_CONTROL__DC_HPD6_INT_POLARITY__SHIFT                      8
#define DC_HPD6_INT_CONTROL__DC_HPD6_INT_EN_MASK                              0x00010000
#define DC_HPD6_INT_CONTROL__DC_HPD6_INT_EN__SHIFT                            16
#define DC_HPD6_INT_CONTROL__DC_HPD6_INT_ACK_MASK                             0x00000001
#define DC_HPD6_INT_CONTROL__DC_HPD6_INT_ACK__SHIFT                           0
#define DC_HPD6_INT_CONTROL__DC_HPD6_RX_INT_EN_MASK                           0x01000000
#define DC_HPD6_INT_CONTROL__DC_HPD6_RX_INT_EN__SHIFT                         24
#define DC_HPD6_INT_CONTROL__DC_HPD6_RX_INT_ACK_MASK                          0x00100000
#define DC_HPD6_INT_CONTROL__DC_HPD6_RX_INT_ACK__SHIFT                        20
#define DC_HPD1_CONTROL__DC_HPD1_RX_INT_TIMER_MASK                            0x3ff0000
#define DC_HPD1_CONTROL__DC_HPD1_RX_INT_TIMER__SHIFT                          0x10
#define DC_HPD1_CONTROL__DC_HPD1_CONNECTION_TIMER_MASK                        0x1fff
#define DC_HPD1_CONTROL__DC_HPD1_CONNECTION_TIMER__SHIFT                      0
#define DC_HPD1_CONTROL__DC_HPD1_EN_MASK                                      0x10000000
#define DC_HPD1_CONTROL__DC_HPD1_EN__SHIFT                                    0x1c
#define DC_HPD2_CONTROL__DC_HPD2_EN_MASK                                      0x10000000
#define DC_HPD2_CONTROL__DC_HPD2_EN__SHIFT                                    0x1c
#define DC_HPD2_CONTROL__DC_HPD2_RX_INT_TIMER_MASK                            0x3ff0000
#define DC_HPD2_CONTROL__DC_HPD2_RX_INT_TIMER__SHIFT                          0x10
#define DC_HPD2_CONTROL__DC_HPD2_CONNECTION_TIMER_MASK                        0x1fff
#define DC_HPD2_CONTROL__DC_HPD2_CONNECTION_TIMER__SHIFT                      0
#define DC_HPD3_CONTROL__DC_HPD3_RX_INT_TIMER_MASK                            0x3ff0000
#define DC_HPD3_CONTROL__DC_HPD3_RX_INT_TIMER__SHIFT                          0x10
#define DC_HPD3_CONTROL__DC_HPD3_EN_MASK                                      0x10000000
#define DC_HPD3_CONTROL__DC_HPD3_EN__SHIFT                                    0x1c
#define DC_HPD3_CONTROL__DC_HPD3_CONNECTION_TIMER_MASK                        0x1fff
#define DC_HPD3_CONTROL__DC_HPD3_CONNECTION_TIMER__SHIFT                      0
#define DC_HPD4_CONTROL__DC_HPD4_RX_INT_TIMER_MASK                            0x3ff0000
#define DC_HPD4_CONTROL__DC_HPD4_RX_INT_TIMER__SHIFT                          0x10
#define DC_HPD4_CONTROL__DC_HPD4_EN_MASK                                      0x10000000
#define DC_HPD4_CONTROL__DC_HPD4_EN__SHIFT                                    0x1c
#define DC_HPD4_CONTROL__DC_HPD4_CONNECTION_TIMER_MASK                        0x1fff
#define DC_HPD4_CONTROL__DC_HPD4_CONNECTION_TIMER__SHIFT                      0
#define DC_HPD5_CONTROL__DC_HPD5_CONNECTION_TIMER_MASK                        0x1fff
#define DC_HPD5_CONTROL__DC_HPD5_CONNECTION_TIMER__SHIFT                      0
#define DC_HPD5_CONTROL__DC_HPD5_EN_MASK                                      0x10000000
#define DC_HPD5_CONTROL__DC_HPD5_EN__SHIFT                                    0x1c
#define DC_HPD5_CONTROL__DC_HPD5_RX_INT_TIMER_MASK                            0x3ff0000
#define DC_HPD5_CONTROL__DC_HPD5_RX_INT_TIMER__SHIFT                          0x10
#define DC_HPD6_CONTROL__DC_HPD6_CONNECTION_TIMER_MASK                        0x1fff
#define DC_HPD6_CONTROL__DC_HPD6_CONNECTION_TIMER__SHIFT                      0
#define DC_HPD6_CONTROL__DC_HPD6_EN_MASK                                      0x10000000
#define DC_HPD6_CONTROL__DC_HPD6_EN__SHIFT                                    0x1c
#define DC_HPD6_CONTROL__DC_HPD6_RX_INT_TIMER_MASK                            0x3ff0000
#define DC_HPD6_CONTROL__DC_HPD6_RX_INT_TIMER__SHIFT                          0x10
#define DPG_PIPE_STUTTER_CONTROL__STUTTER_ENABLE_MASK                         0x00000001
#define DPG_PIPE_STUTTER_CONTROL__STUTTER_ENABLE__SHIFT                       0
#define DCCG_AUDIO_DTO_SOURCE__DCCG_AUDIO_DTO_SEL_MASK                        0x00000010
#define DCCG_AUDIO_DTO_SOURCE__DCCG_AUDIO_DTO_SEL__SHIFT                      4
#define DENTIST_DISPCLK_CNTL__DENTIST_DPREFCLK_WDIVIDER_MASK                  (0x7f << 24)
#define DENTIST_DISPCLK_CNTL__DENTIST_DPREFCLK_WDIVIDER__SHIFT                24
#define FMT_CONTROL__FMT_PIXEL_ENCODING_MASK                                  0x00010000
#define FMT_CONTROL__FMT_PIXEL_ENCODING__SHIFT                                16
#define FMT_BIT_DEPTH_CONTROL__FMT_FRAME_RANDOM_ENABLE_MASK                   0x00002000
#define FMT_BIT_DEPTH_CONTROL__FMT_FRAME_RANDOM_ENABLE__SHIFT                 13
#define FMT_BIT_DEPTH_CONTROL__FMT_SPATIAL_DITHER_DEPTH_MASK                  0x00001000
#define FMT_BIT_DEPTH_CONTROL__FMT_SPATIAL_DITHER_DEPTH__SHIFT                12
#define FMT_BIT_DEPTH_CONTROL__FMT_TRUNCATE_DEPTH_MASK                        0x00000010
#define FMT_BIT_DEPTH_CONTROL__FMT_TRUNCATE_DEPTH__SHIFT                      4
#define FMT_BIT_DEPTH_CONTROL__FMT_RGB_RANDOM_ENABLE_MASK                     0x00004000
#define FMT_BIT_DEPTH_CONTROL__FMT_RGB_RANDOM_ENABLE__SHIFT                   14
#define FMT_BIT_DEPTH_CONTROL__FMT_TEMPORAL_DITHER_EN_MASK                    0x00010000
#define FMT_BIT_DEPTH_CONTROL__FMT_TEMPORAL_DITHER_EN__SHIFT                  16
#define FMT_BIT_DEPTH_CONTROL__FMT_HIGHPASS_RANDOM_ENABLE_MASK                0x00008000
#define FMT_BIT_DEPTH_CONTROL__FMT_HIGHPASS_RANDOM_ENABLE__SHIFT              15
#define FMT_BIT_DEPTH_CONTROL__FMT_TRUNCATE_EN_MASK                           0x00000001
#define FMT_BIT_DEPTH_CONTROL__FMT_TRUNCATE_EN__SHIFT                         0
#define FMT_BIT_DEPTH_CONTROL__FMT_TEMPORAL_LEVEL_MASK                        0x01000000
#define FMT_BIT_DEPTH_CONTROL__FMT_TEMPORAL_LEVEL__SHIFT                      24
#define FMT_BIT_DEPTH_CONTROL__FMT_TEMPORAL_DITHER_RESET_MASK                 0x02000000
#define FMT_BIT_DEPTH_CONTROL__FMT_TEMPORAL_DITHER_RESET__SHIFT               25
#define FMT_BIT_DEPTH_CONTROL__FMT_TEMPORAL_DITHER_DEPTH_MASK                 0x00100000
#define FMT_BIT_DEPTH_CONTROL__FMT_TEMPORAL_DITHER_DEPTH__SHIFT               20
#define FMT_BIT_DEPTH_CONTROL__FMT_SPATIAL_DITHER_EN_MASK                     0x00000100
#define FMT_BIT_DEPTH_CONTROL__FMT_SPATIAL_DITHER_EN__SHIFT                   8
#define FMT_CLAMP_CONTROL__FMT_CLAMP_DATA_EN_MASK                             0x00000001
#define FMT_CLAMP_CONTROL__FMT_CLAMP_DATA_EN__SHIFT                           0
#define D1CRTC_CONTROL__CRTC_EN_MASK                                          0x00000001
#define D1CRTC_CONTROL__CRTC_EN__SHIFT                                        0
#define D1VGA_CONTROL__DVGA_CONTROL_ROTATE_MASK                               0x01000000
#define D1VGA_CONTROL__DVGA_CONTROL_ROTATE__SHIFT                             24
#define D1VGA_CONTROL__DVGA_CONTROL_OVERSCAN_TIMING_SELECT_MASK               0x00000400
#define D1VGA_CONTROL__DVGA_CONTROL_OVERSCAN_TIMING_SELECT__SHIFT             10
#define D1VGA_CONTROL__DVGA_CONTROL_OVERSCAN_COLOR_EN_MASK                    0x00010000
#define D1VGA_CONTROL__DVGA_CONTROL_OVERSCAN_COLOR_EN__SHIFT                  16
#define D1VGA_CONTROL__DVGA_CONTROL_MODE_ENABLE_MASK                          0x00000001
#define D1VGA_CONTROL__DVGA_CONTROL_MODE_ENABLE__SHIFT                        0
#define D1VGA_CONTROL__DVGA_CONTROL_SYNC_POLARITY_SELECT_MASK                 0x00000200
#define D1VGA_CONTROL__DVGA_CONTROL_SYNC_POLARITY_SELECT__SHIFT               9
#define D1VGA_CONTROL__DVGA_CONTROL_TIMING_SELECT_MASK                        0x00000100
#define D1VGA_CONTROL__DVGA_CONTROL_TIMING_SELECT__SHIFT                      8
#define VGA_HDP_CONTROL__VGA_RBBM_LOCK_DISABLE_MASK                           0x00000100
#define VGA_HDP_CONTROL__VGA_RBBM_LOCK_DISABLE__SHIFT                         8
#define VGA_HDP_CONTROL__VGA_MEMORY_DISABLE_MASK                              0x00000010
#define VGA_HDP_CONTROL__VGA_MEMORY_DISABLE__SHIFT                            4
#define VGA_HDP_CONTROL__VGA_SOFT_RESET_MASK                                  0x00010000
#define VGA_HDP_CONTROL__VGA_SOFT_RESET__SHIFT                                16
#define VGA_HDP_CONTROL__VGA_MEM_PAGE_SELECT_EN_MASK                          0x00000001
#define VGA_HDP_CONTROL__VGA_MEM_PAGE_SELECT_EN__SHIFT                        0
#define VGA_RENDER_CONTROL__VGA_VSTATUS_CNTL_MASK                             0x00030000
#define VGA_RENDER_CONTROL__VGA_VSTATUS_CNTL__SHIFT                           16
#define CRTC_CONTROL__CRTC_DISP_READ_REQUEST_DISABLE_MASK                     0x01000000
#define CRTC_CONTROL__CRTC_DISP_READ_REQUEST_DISABLE__SHIFT                   24
#define CRTC_CONTROL__CRTC_MASTER_EN_MASK                                     0x00000001
#define CRTC_CONTROL__CRTC_MASTER_EN__SHIFT                                   0
#define CRTC_BLANK_CONTROL__CRTC_BLANK_DATA_EN_MASK                           0x00000100
#define CRTC_BLANK_CONTROL__CRTC_BLANK_DATA_EN__SHIFT                         8
#define CRTC_STATUS__CRTC_V_BLANK_MASK                                        0x00000001
#define CRTC_STATUS__CRTC_V_BLANK__SHIFT                                      0
#define MASTER_UPDATE_LOCK__MASTER_UPDATE_LOCK_MASK                           0x00000001
#define MASTER_UPDATE_LOCK__MASTER_UPDATE_LOCK__SHIFT                         0
#define MASTER_UPDATE_MODE__MASTER_UPDATE_MODE_MASK                           0x00000007
#define MASTER_UPDATE_MODE__MASTER_UPDATE_MODE__SHIFT                         0
#define GRPH_CONTROL__GRPH_TILE_SPLIT_MASK                                    (0x7 << 13)
#define GRPH_CONTROL__GRPH_TILE_SPLIT__SHIFT                                  13
#define GRPH_CONTROL__GRPH_Z_MASK                                             (0x3 <<4)
#define GRPH_CONTROL__GRPH_Z__SHIFT                                           4
#define GRPH_CONTROL__GRPH_FORMAT_MASK                                        (0x7 << 8)
#define GRPH_CONTROL__GRPH_FORMAT__SHIFT                                      8
#define GRPH_CONTROL__GRPH_ARRAY_MODE_MASK                                    (0x7 << 20)
#define GRPH_CONTROL__GRPH_ARRAY_MODE__SHIFT                                  20
#define GRPH_CONTROL__GRPH_BANK_HEIGHT_MASK                                   (0x3 << 11)
#define GRPH_CONTROL__GRPH_BANK_HEIGHT__SHIFT                                 11
#define GRPH_CONTROL__GRPH_DEPTH_MASK                                         (0x3 << 0)
#define GRPH_CONTROL__GRPH_DEPTH__SHIFT                                       0
#define GRPH_CONTROL__GRPH_BANK_WIDTH_MASK                                    (0x3 << 6)
#define GRPH_CONTROL__GRPH_BANK_WIDTH__SHIFT                                  6
#define GRPH_CONTROL__GRPH_NUM_BANKS_MASK                                     (0x3 << 2)
#define GRPH_CONTROL__GRPH_NUM_BANKS__SHIFT                                   2
#define GRPH_CONTROL__GRPH_MACRO_TILE_ASPECT_MASK                             (0x3 << 18)
#define GRPH_CONTROL__GRPH_MACRO_TILE_ASPECT__SHIFT                           18
#define GRPH_LUT_10BIT_BYPASS_CONTROL__LUT_10BIT_BYPASS_EN_MASK               0x00000100
#define GRPH_LUT_10BIT_BYPASS_CONTROL__LUT_10BIT_BYPASS_EN__SHIFT             8
#define GRPH_SWAP_CONTROL__GRPH_BLUE_CROSSBAR_MASK                            (0x3 << 8)
#define GRPH_SWAP_CONTROL__GRPH_BLUE_CROSSBAR__SHIFT                          8
#define GRPH_SWAP_CONTROL__GRPH_ALPHA_CROSSBAR_MASK                           (0x3 << 10)
#define GRPH_SWAP_CONTROL__GRPH_ALPHA_CROSSBAR__SHIFT                         10
#define GRPH_SWAP_CONTROL__GRPH_GREEN_CROSSBAR_MASK                           (0x3 << 6)
#define GRPH_SWAP_CONTROL__GRPH_GREEN_CROSSBAR__SHIFT                         6
#define GRPH_SWAP_CONTROL__GRPH_RED_CROSSBAR_MASK                             (0x3 << 4)
#define GRPH_SWAP_CONTROL__GRPH_RED_CROSSBAR__SHIFT                           4
#define GRPH_SWAP_CONTROL__GRPH_ENDIAN_SWAP_MASK                              (0x3 << 0)
#define GRPH_SWAP_CONTROL__GRPH_ENDIAN_SWAP__SHIFT                            0
#define GRPH_SECONDARY_SURFACE_ADDRESS__GRPH_SURFACE_ADDRESS_MASK             0xffffff00
#define GRPH_SECONDARY_SURFACE_ADDRESS__GRPH_SURFACE_ADDRESS__SHIFT           8
#define GRPH_SECONDARY_SURFACE_ADDRESS__GRPH_DFQ_ENABLE_MASK                  0x00000001
#define GRPH_SECONDARY_SURFACE_ADDRESS__GRPH_DFQ_ENABLE__SHIFT                0
#define GRPH_UPDATE__GRPH_SURFACE_UPDATE_PENDING_MASK                         0x00000004
#define GRPH_UPDATE__GRPH_SURFACE_UPDATE_PENDING__SHIFT                       2
#define GRPH_UPDATE__GRPH_UPDATE_LOCK_MASK                                    0x00010000
#define GRPH_UPDATE__GRPH_UPDATE_LOCK__SHIFT                                  16
#define GRPH_FLIP_CONTROL__GRPH_SURFACE_UPDATE_H_RETRACE_EN_MASK              0x00000001
#define GRPH_FLIP_CONTROL__GRPH_SURFACE_UPDATE_H_RETRACE_EN__SHIFT            0
#define LB_DATA_FORMAT__INTERLEAVE_EN_MASK                                    0x00000001
#define LB_DATA_FORMAT__INTERLEAVE_EN__SHIFT                                  0
#define CUR_CONTROL__CURSOR_EN_MASK                                           0x00000001
#define CUR_CONTROL__CURSOR_EN__SHIFT                                         0
#define CUR_CONTROL__CURSOR_2X_MAGNIFY_MASK                                   0x00010000
#define CUR_CONTROL__CURSOR_2X_MAGNIFY__SHIFT                                 16
#define CUR_CONTROL__CURSOR_MODE_MASK                                         (0x3 << 8)
#define CUR_CONTROL__CURSOR_MODE__SHIFT                                       8
#define CUR_CONTROL__CURSOR_URGENT_CONTROL_MASK                               (0x7 << 24)
#define CUR_CONTROL__CURSOR_URGENT_CONTROL__SHIFT                             24
#define CUR_CONTROL__CURSOR_FORCE_MC_ON_MASK                                  0x00100000
#define CUR_CONTROL__CURSOR_FORCE_MC_ON__SHIFT                                20
#define CUR_UPDATE__CURSOR_DISABLE_MULTIPLE_UPDATE_MASK                       0x01000000
#define CUR_UPDATE__CURSOR_DISABLE_MULTIPLE_UPDATE__SHIFT                     24
#define CUR_UPDATE__CURSOR_UPDATE_PENDING_MASK                                0x00000001
#define CUR_UPDATE__CURSOR_UPDATE_PENDING__SHIFT                              0
#define CUR_UPDATE__CURSOR_UPDATE_TAKEN_MASK                                  0x00000002
#define CUR_UPDATE__CURSOR_UPDATE_TAKEN__SHIFT                                1
#define CUR_UPDATE__CURSOR_UPDATE_LOCK_MASK                                   0x00010000
#define CUR_UPDATE__CURSOR_UPDATE_LOCK__SHIFT                                 16

#endif /*__DCE_6_0_SH_MASK_H__*/
