#ifndef __DCE_6_0_D_H__
#define __DCE_6_0_D_H__

#define mmDCCG_DISP_SLOW_SELECT_REG                                             0x13f
#define mmPIPE0_DMIF_BUFFER_CONTROL                                             0x328
#define mmAZ_F0_CODEC_ENDPOINT_INDEX                                            0x1780
#define mmAZ_F0_CODEC_ENDPOINT_DATA                                             0x1781
#define mmAZ_F0_CODEC_PIN_CONTROL_AUDIO_DESCRIPTOR0                             0xa
#define mmAZ_F0_CODEC_PIN_CONTROL_AUDIO_DESCRIPTOR4                             0xb
#define mmAZ_F0_CODEC_PIN_CONTROL_AUDIO_DESCRIPTOR8                             0xc
#define mmAZ_F0_CODEC_PIN_CONTROL_AUDIO_DESCRIPTOR12                            0xd
#define mmAZ_F0_CODEC_PIN_CONTROL_RESPONSE_HBR                                  0xe
#define mmAZ_F0_CODEC_PIN_CONTROL_SINK_INFO2                                    0xf
#define mmAZ_F0_CODEC_PIN_CONTROL_SINK_INFO6                                    0x10
#define mmAZ_F0_CODEC_PIN_CONTROL_HOT_PLUG_CONTROL                              0x15
#define mmDC_LB_MEMORY_SPLIT                                                    0x1ac3
#define mmPRIORITY_A_CNT                                                        0x1ac6
#define mmPRIORITY_B_CNT                                                        0x1ac7
#define mmDPG_PIPE_ARBITRATION_CONTROL3                                         0x1b32
#define mmDPG_PIPE_LATENCY_CONTROL                                              0x1b33
#define mmLB_VLINE_STATUS                                                       0x1aee
#define mmLB_VBLANK_STATUS                                                      0x1aef
#define mmLB_INT_MASK                                                           0x1ad0
#define mmDISP_INTERRUPT_STATUS                                                 0x183d
#define mmDISP_INTERRUPT_STATUS_CONTINUE                                        0x183e
#define mmDISP_INTERRUPT_STATUS_CONTINUE2                                       0x183f
#define mmDISP_INTERRUPT_STATUS_CONTINUE3                                       0x1840
#define mmDISP_INTERRUPT_STATUS_CONTINUE4                                       0x1853
#define mmDISP_INTERRUPT_STATUS_CONTINUE5                                       0x1854
#define mmGRPH_INT_STATUS                                                       0x1a16
#define mmGRPH_INT_CONTROL                                                      0x1a17
#define mmDAC_AUTODETECT_INT_CONTROL                                            0x19f2
#define mmDC_HPD1_INT_STATUS                                                    0x1807
#define mmDC_HPD2_INT_STATUS                                                    0x180a
#define mmDC_HPD3_INT_STATUS                                                    0x180d
#define mmDC_HPD4_INT_STATUS                                                    0x1810
#define mmDC_HPD5_INT_STATUS                                                    0x1813
#define mmDC_HPD6_INT_STATUS                                                    0x1816
#define mmDC_HPD1_INT_CONTROL                                                   0x1808
#define mmDC_HPD2_INT_CONTROL                                                   0x180b
#define mmDC_HPD3_INT_CONTROL                                                   0x180e
#define mmDC_HPD4_INT_CONTROL                                                   0x1811
#define mmDC_HPD5_INT_CONTROL                                                   0x1814
#define mmDC_HPD6_INT_CONTROL                                                   0x1817
#define mmDC_HPD1_CONTROL                                                       0x1809
#define mmDC_HPD2_CONTROL                                                       0x180c
#define mmDC_HPD3_CONTROL                                                       0x180f
#define mmDC_HPD4_CONTROL                                                       0x1812
#define mmDC_HPD5_CONTROL                                                       0x1815
#define mmDC_HPD6_CONTROL                                                       0x1818
#define mmDPG_PIPE_STUTTER_CONTROL                                              0x1b35
#define mmCRTC_STATUS_FRAME_COUNT                                               0x1ba6
#define mmDCCG_AUDIO_DTO_SOURCE                                                 0x16b
#define mmDCCG_AUDIO_DTO0_PHASE                                                 0x16c
#define mmDCCG_AUDIO_DTO0_MODULE                                                0x16d
#define mmDCCG_AUDIO_DTO1_PHASE                                                 0x170
#define mmDCCG_AUDIO_DTO1_MODULE                                                0x171
#define mmDENTIST_DISPCLK_CNTL                                                  0x124
#define mmAFMT_AUDIO_SRC_CONTROL                                                0x1c4f
#define mmFMT_CONTROL                                                           0x19c0
#define mmFMT_BIT_DEPTH_CONTROL                                                 0x19c4
#define mmFMT_CLAMP_CONTROL                                                     0x19cb
#define mmD1CRTC_CONTROL                                                        0x1820
#define mmD1CRTC_STATUS                                                         0x1827
#define mmD1CRTC_UPDATE_LOCK                                                    0x183a
#define mmD2CRTC_CONTROL                                                        0x1a20
#define mmD2CRTC_STATUS                                                         0x1a27
#define mmD2CRTC_UPDATE_LOCK                                                    0x1a3a
#define mmD1VGA_CONTROL                                                         0xcc
#define mmD2VGA_CONTROL                                                         0xce
#define mmVGA_HDP_CONTROL                                                       0xca
#define mmVGA_MEMORY_BASE_ADDRESS                                               0xc4
#define mmVGA_RENDER_CONTROL                                                    0xc0
#define mmVGA_MEMORY_BASE_ADDRESS                                               0xc4
#define mmVGA_MEMORY_BASE_ADDRESS_HIGH                                          0xc9
#define mmD3VGA_CONTROL                                                         0xf8
#define mmD4VGA_CONTROL                                                         0xf9
#define mmD5VGA_CONTROL                                                         0xfa
#define mmD6VGA_CONTROL                                                         0xfb
#define mmCRTC_V_BLANK_START_END                                                0x1b8d
#define mmCRTC_CONTROL                                                          0x1b9c
#define mmCRTC_BLANK_CONTROL                                                    0x1b9d
#define mmCRTC_STATUS                                                           0x1ba3
#define mmCRTC_STATUS_POSITION                                                  0x1ba4
#define mmCRTC_STATUS_HV_COUNT                                                  0x1ba8
#define mmCRTC_UPDATE_LOCK                                                      0x1bb5
#define mmMASTER_UPDATE_LOCK                                                    0x1bbd
#define mmMASTER_UPDATE_MODE                                                    0x1bbe
#define mmDC_GPIO_HPD_MASK                                                      0x192c
#define mmDC_GPIO_HPD_A                                                         0x192d
#define mmDC_GPIO_HPD_EN                                                        0x192e
#define mmDC_GPIO_HPD_Y                                                         0x192f
#define mmGRPH_ENABLE                                                           0x1a00
#define mmGRPH_CONTROL                                                          0x1a01
#define mmGRPH_LUT_10BIT_BYPASS_CONTROL                                         0x1a02
#define mmGRPH_SWAP_CONTROL                                                     0x1a03
#define mmGRPH_PRIMARY_SURFACE_ADDRESS                                          0x1a04
#define mmGRPH_SECONDARY_SURFACE_ADDRESS                                        0x1a05
#define mmGRPH_PITCH                                                            0x1a06
#define mmGRPH_PRIMARY_SURFACE_ADDRESS_HIGH                                     0x1a07
#define mmGRPH_SECONDARY_SURFACE_ADDRESS_HIGH                                   0x1a08
#define mmGRPH_SURFACE_OFFSET_X                                                 0x1a09
#define mmGRPH_SURFACE_OFFSET_Y                                                 0x1a0a
#define mmGRPH_X_START                                                          0x1a0b
#define mmGRPH_Y_START                                                          0x1a0c
#define mmGRPH_X_END                                                            0x1a0d
#define mmGRPH_Y_END                                                            0x1a0e
#define mmGRPH_UPDATE                                                           0x1a11
#define mmGRPH_FLIP_CONTROL                                                     0x1a12
#define mmDC_LUT_RW_MODE                                                        0x1a78
#define mmDC_LUT_RW_INDEX                                                       0x1a79
#define mmDC_LUT_SEQ_COLOR                                                      0x1a7a
#define mmDC_LUT_PWL_DATA                                                       0x1a7b
#define mmDC_LUT_30_COLOR                                                       0x1a7c
#define mmDC_LUT_VGA_ACCESS_ENABLE                                              0x1a7d
#define mmDC_LUT_WRITE_EN_MASK                                                  0x1a7e
#define mmDC_LUT_AUTOFILL                                                       0x1a7f
#define mmDC_LUT_CONTROL                                                        0x1a80
#define mmDC_LUT_BLACK_OFFSET_BLUE                                              0x1a81
#define mmDC_LUT_BLACK_OFFSET_GREEN                                             0x1a82
#define mmDC_LUT_BLACK_OFFSET_RED                                               0x1a83
#define mmDC_LUT_WHITE_OFFSET_BLUE                                              0x1a84
#define mmDC_LUT_WHITE_OFFSET_GREEN                                             0x1a85
#define mmDC_LUT_WHITE_OFFSET_RED                                               0x1a86
#define mmDESKTOP_HEIGHT                                                        0x1ac1
#define mmVIEWPORT_START                                                        0x1b5c
#define mmVIEWPORT_SIZE                                                         0x1b5d
#define mmLB_DATA_FORMAT                                                        0x1ac0
#define mmCUR_CONTROL                                                           0x1a66
#define mmCUR_SURFACE_ADDRESS                                                   0x1a67
#define mmCUR_SIZE                                                              0x1a68
#define mmCUR_SURFACE_ADDRESS_HIGH                                              0x1a69
#define mmCUR_POSITION                                                          0x1a6a
#define mmCUR_HOT_SPOT                                                          0x1a6b
#define mmCUR_COLOR1                                                            0x1a6c
#define mmCUR_COLOR2                                                            0x1a6d
#define mmCUR_UPDATE                                                            0x1a6e

#endif /*__DCE_6_0_D_H__*/
